#pragma once
// clang-format off
// Generated by 'wlgen' from '/nix/store/vv8mrvh447wpapvim5adif1izf57f3sw-wayland-scanner-1.24.0/share/wayland/wayland.xml' from '/nix/store/1hjwhmhrv1nshdm4n674rrllva5khv5d-wayland-protocols-1.45/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml'.

#include "core/forward.h"

struct wl_message {
  const char*                 name;
  const char*                 signature;
  const struct wl_interface** types;
};

struct wl_interface {
  const char*              name;
  int                      version;
  int                      method_count;
  const struct wl_message* methods;
  int                      event_count;
  const struct wl_message* events;
};

struct wl_array {
  usize size, alloc;
  void* data;
};

// Flag to destroy the proxy when marshalling a request (from wayland-client-core.h).
#define WL_MARSHAL_FLAG_DESTROY (1 << 0)

// Low-level libwayland types not present in the protocol XML.
struct wl_proxy;
struct wl_display;
struct wl_registry;

// Function table for libwayland-client symbols, populated by wlLoad().
typedef struct {
  struct wl_display*  (SYS_DECL* display_connect)(const char* name);
  void                (SYS_DECL* display_disconnect)(struct wl_display*);
  int                 (SYS_DECL* display_dispatch)(struct wl_display*);
  int                 (SYS_DECL* display_dispatch_pending)(struct wl_display*);
  int                 (SYS_DECL* display_roundtrip)(struct wl_display*);
  int                 (SYS_DECL* display_flush)(struct wl_display*);
  int                 (SYS_DECL* proxy_add_listener)(struct wl_proxy*, void(**)(void), void*);
  void*               (SYS_DECL* proxy_marshal_flags)(struct wl_proxy*, u32, const struct wl_interface*, u32, u32, ...);
  u32                 (SYS_DECL* proxy_get_version)(struct wl_proxy*);
  void                (SYS_DECL* proxy_destroy)(struct wl_proxy*);
} WlFuncs;

bool wlLoad(const DynLib* lib, WlFuncs* out);

// Bind a registry global, capping at maxVersion.
void* wlRegistryBind(WlFuncs*, struct wl_registry*, u32 name, u32 version, const struct wl_interface*, u32 maxVersion);

// Forward declarations.
struct wl_display;
struct wl_registry;
struct wl_callback;
struct wl_compositor;
struct wl_shm_pool;
struct wl_shm;
struct wl_buffer;
struct wl_data_offer;
struct wl_data_source;
struct wl_data_device;
struct wl_data_device_manager;
struct wl_shell;
struct wl_shell_surface;
struct wl_surface;
struct wl_seat;
struct wl_pointer;
struct wl_keyboard;
struct wl_touch;
struct wl_output;
struct wl_region;
struct wl_subcompositor;
struct wl_subsurface;
struct wl_fixes;
struct xdg_wm_base;
struct xdg_positioner;
struct xdg_surface;
struct xdg_toplevel;
struct xdg_popup;

// Interface objects (defined in the generated .c file).
extern const struct wl_interface wl_display_interface;
extern const struct wl_interface wl_registry_interface;
extern const struct wl_interface wl_callback_interface;
extern const struct wl_interface wl_compositor_interface;
extern const struct wl_interface wl_shm_pool_interface;
extern const struct wl_interface wl_shm_interface;
extern const struct wl_interface wl_buffer_interface;
extern const struct wl_interface wl_data_offer_interface;
extern const struct wl_interface wl_data_source_interface;
extern const struct wl_interface wl_data_device_interface;
extern const struct wl_interface wl_data_device_manager_interface;
extern const struct wl_interface wl_shell_interface;
extern const struct wl_interface wl_shell_surface_interface;
extern const struct wl_interface wl_surface_interface;
extern const struct wl_interface wl_seat_interface;
extern const struct wl_interface wl_pointer_interface;
extern const struct wl_interface wl_keyboard_interface;
extern const struct wl_interface wl_touch_interface;
extern const struct wl_interface wl_output_interface;
extern const struct wl_interface wl_region_interface;
extern const struct wl_interface wl_subcompositor_interface;
extern const struct wl_interface wl_subsurface_interface;
extern const struct wl_interface wl_fixes_interface;
extern const struct wl_interface xdg_wm_base_interface;
extern const struct wl_interface xdg_positioner_interface;
extern const struct wl_interface xdg_surface_interface;
extern const struct wl_interface xdg_toplevel_interface;
extern const struct wl_interface xdg_popup_interface;

// wl_display - enums.
enum wl_display_error {
  WL_DISPLAY_ERROR_INVALID_OBJECT = 0,
  WL_DISPLAY_ERROR_INVALID_METHOD = 1,
  WL_DISPLAY_ERROR_NO_MEMORY = 2,
  WL_DISPLAY_ERROR_IMPLEMENTATION = 3,
};

// wl_display - request opcodes.
#define WL_DISPLAY_SYNC 0
#define WL_DISPLAY_GET_REGISTRY 1

// wl_display - listener.
struct wl_display_listener {
  void (*error)(void* data, struct wl_display*, void* object_id, u32 code, const char* message);
  void (*delete_id)(void* data, struct wl_display*, u32 id);
};

// wl_display - utility wrappers.
u32 wl_display_get_version(WlFuncs* api, struct wl_display* obj);
void wl_display_destroy(WlFuncs* api, struct wl_display* obj);
void wl_display_add_listener(WlFuncs* api, struct wl_display* obj, const struct wl_display_listener* listener, void* data);

// wl_display - request wrappers.
struct wl_callback* wl_display_sync(WlFuncs* api, struct wl_display* obj);
struct wl_registry* wl_display_get_registry(WlFuncs* api, struct wl_display* obj);

// wl_registry - request opcodes.
#define WL_REGISTRY_BIND 0

// wl_registry - listener.
struct wl_registry_listener {
  void (*global)(void* data, struct wl_registry*, u32 name, const char* interface, u32 version);
  void (*global_remove)(void* data, struct wl_registry*, u32 name);
};

// wl_registry - utility wrappers.
u32 wl_registry_get_version(WlFuncs* api, struct wl_registry* obj);
void wl_registry_destroy(WlFuncs* api, struct wl_registry* obj);
void wl_registry_add_listener(WlFuncs* api, struct wl_registry* obj, const struct wl_registry_listener* listener, void* data);

// wl_callback - listener.
struct wl_callback_listener {
  void (*done)(void* data, struct wl_callback*, u32 callback_data);
};

// wl_callback - utility wrappers.
u32 wl_callback_get_version(WlFuncs* api, struct wl_callback* obj);
void wl_callback_destroy(WlFuncs* api, struct wl_callback* obj);
void wl_callback_add_listener(WlFuncs* api, struct wl_callback* obj, const struct wl_callback_listener* listener, void* data);

// wl_compositor - request opcodes.
#define WL_COMPOSITOR_CREATE_SURFACE 0
#define WL_COMPOSITOR_CREATE_REGION 1

// wl_compositor - utility wrappers.
u32 wl_compositor_get_version(WlFuncs* api, struct wl_compositor* obj);
void wl_compositor_destroy(WlFuncs* api, struct wl_compositor* obj);

// wl_compositor - request wrappers.
struct wl_surface* wl_compositor_create_surface(WlFuncs* api, struct wl_compositor* obj);
struct wl_region* wl_compositor_create_region(WlFuncs* api, struct wl_compositor* obj);

// wl_shm_pool - request opcodes.
#define WL_SHM_POOL_CREATE_BUFFER 0
#define WL_SHM_POOL_DESTROY 1
#define WL_SHM_POOL_RESIZE 2

// wl_shm_pool - utility wrappers.
u32 wl_shm_pool_get_version(WlFuncs* api, struct wl_shm_pool* obj);

// wl_shm_pool - request wrappers.
struct wl_buffer* wl_shm_pool_create_buffer(WlFuncs* api, struct wl_shm_pool* obj, i32 offset, i32 width, i32 height, i32 stride, u32 format);
void wl_shm_pool_destroy(WlFuncs* api, struct wl_shm_pool* obj);
void wl_shm_pool_resize(WlFuncs* api, struct wl_shm_pool* obj, i32 size);

// wl_shm - enums.
enum wl_shm_error {
  WL_SHM_ERROR_INVALID_FORMAT = 0,
  WL_SHM_ERROR_INVALID_STRIDE = 1,
  WL_SHM_ERROR_INVALID_FD = 2,
};
enum wl_shm_format {
  WL_SHM_FORMAT_ARGB8888 = 0,
  WL_SHM_FORMAT_XRGB8888 = 1,
  WL_SHM_FORMAT_C8 = 538982467,
  WL_SHM_FORMAT_RGB332 = 943867730,
  WL_SHM_FORMAT_BGR233 = 944916290,
  WL_SHM_FORMAT_XRGB4444 = 842093144,
  WL_SHM_FORMAT_XBGR4444 = 842089048,
  WL_SHM_FORMAT_RGBX4444 = 842094674,
  WL_SHM_FORMAT_BGRX4444 = 842094658,
  WL_SHM_FORMAT_ARGB4444 = 842093121,
  WL_SHM_FORMAT_ABGR4444 = 842089025,
  WL_SHM_FORMAT_RGBA4444 = 842088786,
  WL_SHM_FORMAT_BGRA4444 = 842088770,
  WL_SHM_FORMAT_XRGB1555 = 892424792,
  WL_SHM_FORMAT_XBGR1555 = 892420696,
  WL_SHM_FORMAT_RGBX5551 = 892426322,
  WL_SHM_FORMAT_BGRX5551 = 892426306,
  WL_SHM_FORMAT_ARGB1555 = 892424769,
  WL_SHM_FORMAT_ABGR1555 = 892420673,
  WL_SHM_FORMAT_RGBA5551 = 892420434,
  WL_SHM_FORMAT_BGRA5551 = 892420418,
  WL_SHM_FORMAT_RGB565 = 909199186,
  WL_SHM_FORMAT_BGR565 = 909199170,
  WL_SHM_FORMAT_RGB888 = 875710290,
  WL_SHM_FORMAT_BGR888 = 875710274,
  WL_SHM_FORMAT_XBGR8888 = 875709016,
  WL_SHM_FORMAT_RGBX8888 = 875714642,
  WL_SHM_FORMAT_BGRX8888 = 875714626,
  WL_SHM_FORMAT_ABGR8888 = 875708993,
  WL_SHM_FORMAT_RGBA8888 = 875708754,
  WL_SHM_FORMAT_BGRA8888 = 875708738,
  WL_SHM_FORMAT_XRGB2101010 = 808669784,
  WL_SHM_FORMAT_XBGR2101010 = 808665688,
  WL_SHM_FORMAT_RGBX1010102 = 808671314,
  WL_SHM_FORMAT_BGRX1010102 = 808671298,
  WL_SHM_FORMAT_ARGB2101010 = 808669761,
  WL_SHM_FORMAT_ABGR2101010 = 808665665,
  WL_SHM_FORMAT_RGBA1010102 = 808665426,
  WL_SHM_FORMAT_BGRA1010102 = 808665410,
  WL_SHM_FORMAT_YUYV = 1448695129,
  WL_SHM_FORMAT_YVYU = 1431918169,
  WL_SHM_FORMAT_UYVY = 1498831189,
  WL_SHM_FORMAT_VYUY = 1498765654,
  WL_SHM_FORMAT_AYUV = 1448433985,
  WL_SHM_FORMAT_NV12 = 842094158,
  WL_SHM_FORMAT_NV21 = 825382478,
  WL_SHM_FORMAT_NV16 = 909203022,
  WL_SHM_FORMAT_NV61 = 825644622,
  WL_SHM_FORMAT_YUV410 = 961959257,
  WL_SHM_FORMAT_YVU410 = 961893977,
  WL_SHM_FORMAT_YUV411 = 825316697,
  WL_SHM_FORMAT_YVU411 = 825316953,
  WL_SHM_FORMAT_YUV420 = 842093913,
  WL_SHM_FORMAT_YVU420 = 842094169,
  WL_SHM_FORMAT_YUV422 = 909202777,
  WL_SHM_FORMAT_YVU422 = 909203033,
  WL_SHM_FORMAT_YUV444 = 875713881,
  WL_SHM_FORMAT_YVU444 = 875714137,
  WL_SHM_FORMAT_R8 = 538982482,
  WL_SHM_FORMAT_R16 = 540422482,
  WL_SHM_FORMAT_RG88 = 943212370,
  WL_SHM_FORMAT_GR88 = 943215175,
  WL_SHM_FORMAT_RG1616 = 842221394,
  WL_SHM_FORMAT_GR1616 = 842224199,
  WL_SHM_FORMAT_XRGB16161616F = 1211388504,
  WL_SHM_FORMAT_XBGR16161616F = 1211384408,
  WL_SHM_FORMAT_ARGB16161616F = 1211388481,
  WL_SHM_FORMAT_ABGR16161616F = 1211384385,
  WL_SHM_FORMAT_XYUV8888 = 1448434008,
  WL_SHM_FORMAT_VUY888 = 875713878,
  WL_SHM_FORMAT_VUY101010 = 808670550,
  WL_SHM_FORMAT_Y210 = 808530521,
  WL_SHM_FORMAT_Y212 = 842084953,
  WL_SHM_FORMAT_Y216 = 909193817,
  WL_SHM_FORMAT_Y410 = 808531033,
  WL_SHM_FORMAT_Y412 = 842085465,
  WL_SHM_FORMAT_Y416 = 909194329,
  WL_SHM_FORMAT_XVYU2101010 = 808670808,
  WL_SHM_FORMAT_XVYU12_16161616 = 909334104,
  WL_SHM_FORMAT_XVYU16161616 = 942954072,
  WL_SHM_FORMAT_Y0L0 = 810299481,
  WL_SHM_FORMAT_X0L0 = 810299480,
  WL_SHM_FORMAT_Y0L2 = 843853913,
  WL_SHM_FORMAT_X0L2 = 843853912,
  WL_SHM_FORMAT_YUV420_8BIT = 942691673,
  WL_SHM_FORMAT_YUV420_10BIT = 808539481,
  WL_SHM_FORMAT_XRGB8888_A8 = 943805016,
  WL_SHM_FORMAT_XBGR8888_A8 = 943800920,
  WL_SHM_FORMAT_RGBX8888_A8 = 943806546,
  WL_SHM_FORMAT_BGRX8888_A8 = 943806530,
  WL_SHM_FORMAT_RGB888_A8 = 943798354,
  WL_SHM_FORMAT_BGR888_A8 = 943798338,
  WL_SHM_FORMAT_RGB565_A8 = 943797586,
  WL_SHM_FORMAT_BGR565_A8 = 943797570,
  WL_SHM_FORMAT_NV24 = 875714126,
  WL_SHM_FORMAT_NV42 = 842290766,
  WL_SHM_FORMAT_P210 = 808530512,
  WL_SHM_FORMAT_P010 = 808530000,
  WL_SHM_FORMAT_P012 = 842084432,
  WL_SHM_FORMAT_P016 = 909193296,
  WL_SHM_FORMAT_AXBXGXRX106106106106 = 808534593,
  WL_SHM_FORMAT_NV15 = 892425806,
  WL_SHM_FORMAT_Q410 = 808531025,
  WL_SHM_FORMAT_Q401 = 825242705,
  WL_SHM_FORMAT_XRGB16161616 = 942953048,
  WL_SHM_FORMAT_XBGR16161616 = 942948952,
  WL_SHM_FORMAT_ARGB16161616 = 942953025,
  WL_SHM_FORMAT_ABGR16161616 = 942948929,
  WL_SHM_FORMAT_C1 = 538980675,
  WL_SHM_FORMAT_C2 = 538980931,
  WL_SHM_FORMAT_C4 = 538981443,
  WL_SHM_FORMAT_D1 = 538980676,
  WL_SHM_FORMAT_D2 = 538980932,
  WL_SHM_FORMAT_D4 = 538981444,
  WL_SHM_FORMAT_D8 = 538982468,
  WL_SHM_FORMAT_R1 = 538980690,
  WL_SHM_FORMAT_R2 = 538980946,
  WL_SHM_FORMAT_R4 = 538981458,
  WL_SHM_FORMAT_R10 = 540029266,
  WL_SHM_FORMAT_R12 = 540160338,
  WL_SHM_FORMAT_AVUY8888 = 1498764865,
  WL_SHM_FORMAT_XVUY8888 = 1498764888,
  WL_SHM_FORMAT_P030 = 808661072,
};

// wl_shm - request opcodes.
#define WL_SHM_CREATE_POOL 0
#define WL_SHM_RELEASE 1

// wl_shm - listener.
struct wl_shm_listener {
  void (*format)(void* data, struct wl_shm*, u32 format);
};

// wl_shm - utility wrappers.
u32 wl_shm_get_version(WlFuncs* api, struct wl_shm* obj);
void wl_shm_add_listener(WlFuncs* api, struct wl_shm* obj, const struct wl_shm_listener* listener, void* data);

// wl_shm - request wrappers.
struct wl_shm_pool* wl_shm_create_pool(WlFuncs* api, struct wl_shm* obj, i32 fd, i32 size);
void wl_shm_release(WlFuncs* api, struct wl_shm* obj);

// wl_buffer - request opcodes.
#define WL_BUFFER_DESTROY 0

// wl_buffer - listener.
struct wl_buffer_listener {
  void (*release)(void* data, struct wl_buffer*);
};

// wl_buffer - utility wrappers.
u32 wl_buffer_get_version(WlFuncs* api, struct wl_buffer* obj);
void wl_buffer_add_listener(WlFuncs* api, struct wl_buffer* obj, const struct wl_buffer_listener* listener, void* data);

// wl_buffer - request wrappers.
void wl_buffer_destroy(WlFuncs* api, struct wl_buffer* obj);

// wl_data_offer - enums.
enum wl_data_offer_error {
  WL_DATA_OFFER_ERROR_INVALID_FINISH = 0,
  WL_DATA_OFFER_ERROR_INVALID_ACTION_MASK = 1,
  WL_DATA_OFFER_ERROR_INVALID_ACTION = 2,
  WL_DATA_OFFER_ERROR_INVALID_OFFER = 3,
};

// wl_data_offer - request opcodes.
#define WL_DATA_OFFER_ACCEPT 0
#define WL_DATA_OFFER_RECEIVE 1
#define WL_DATA_OFFER_DESTROY 2
#define WL_DATA_OFFER_FINISH 3
#define WL_DATA_OFFER_SET_ACTIONS 4

// wl_data_offer - listener.
struct wl_data_offer_listener {
  void (*offer)(void* data, struct wl_data_offer*, const char* mime_type);
  void (*source_actions)(void* data, struct wl_data_offer*, u32 source_actions);
  void (*action)(void* data, struct wl_data_offer*, u32 dnd_action);
};

// wl_data_offer - utility wrappers.
u32 wl_data_offer_get_version(WlFuncs* api, struct wl_data_offer* obj);
void wl_data_offer_add_listener(WlFuncs* api, struct wl_data_offer* obj, const struct wl_data_offer_listener* listener, void* data);

// wl_data_offer - request wrappers.
void wl_data_offer_accept(WlFuncs* api, struct wl_data_offer* obj, u32 serial, const char* mime_type);
void wl_data_offer_receive(WlFuncs* api, struct wl_data_offer* obj, const char* mime_type, i32 fd);
void wl_data_offer_destroy(WlFuncs* api, struct wl_data_offer* obj);
void wl_data_offer_finish(WlFuncs* api, struct wl_data_offer* obj);
void wl_data_offer_set_actions(WlFuncs* api, struct wl_data_offer* obj, u32 dnd_actions, u32 preferred_action);

// wl_data_source - enums.
enum wl_data_source_error {
  WL_DATA_SOURCE_ERROR_INVALID_ACTION_MASK = 0,
  WL_DATA_SOURCE_ERROR_INVALID_SOURCE = 1,
};

// wl_data_source - request opcodes.
#define WL_DATA_SOURCE_OFFER 0
#define WL_DATA_SOURCE_DESTROY 1
#define WL_DATA_SOURCE_SET_ACTIONS 2

// wl_data_source - listener.
struct wl_data_source_listener {
  void (*target)(void* data, struct wl_data_source*, const char* mime_type);
  void (*send)(void* data, struct wl_data_source*, const char* mime_type, i32 fd);
  void (*cancelled)(void* data, struct wl_data_source*);
  void (*dnd_drop_performed)(void* data, struct wl_data_source*);
  void (*dnd_finished)(void* data, struct wl_data_source*);
  void (*action)(void* data, struct wl_data_source*, u32 dnd_action);
};

// wl_data_source - utility wrappers.
u32 wl_data_source_get_version(WlFuncs* api, struct wl_data_source* obj);
void wl_data_source_add_listener(WlFuncs* api, struct wl_data_source* obj, const struct wl_data_source_listener* listener, void* data);

// wl_data_source - request wrappers.
void wl_data_source_offer(WlFuncs* api, struct wl_data_source* obj, const char* mime_type);
void wl_data_source_destroy(WlFuncs* api, struct wl_data_source* obj);
void wl_data_source_set_actions(WlFuncs* api, struct wl_data_source* obj, u32 dnd_actions);

// wl_data_device - enums.
enum wl_data_device_error {
  WL_DATA_DEVICE_ERROR_ROLE = 0,
  WL_DATA_DEVICE_ERROR_USED_SOURCE = 1,
};

// wl_data_device - request opcodes.
#define WL_DATA_DEVICE_START_DRAG 0
#define WL_DATA_DEVICE_SET_SELECTION 1
#define WL_DATA_DEVICE_RELEASE 2

// wl_data_device - listener.
struct wl_data_device_listener {
  void (*data_offer)(void* data, struct wl_data_device*, struct wl_data_offer* id);
  void (*enter)(void* data, struct wl_data_device*, u32 serial, struct wl_surface* surface, i32 x, i32 y, struct wl_data_offer* id);
  void (*leave)(void* data, struct wl_data_device*);
  void (*motion)(void* data, struct wl_data_device*, u32 time, i32 x, i32 y);
  void (*drop)(void* data, struct wl_data_device*);
  void (*selection)(void* data, struct wl_data_device*, struct wl_data_offer* id);
};

// wl_data_device - utility wrappers.
u32 wl_data_device_get_version(WlFuncs* api, struct wl_data_device* obj);
void wl_data_device_add_listener(WlFuncs* api, struct wl_data_device* obj, const struct wl_data_device_listener* listener, void* data);

// wl_data_device - request wrappers.
void wl_data_device_start_drag(WlFuncs* api, struct wl_data_device* obj, struct wl_data_source* source, struct wl_surface* origin, struct wl_surface* icon, u32 serial);
void wl_data_device_set_selection(WlFuncs* api, struct wl_data_device* obj, struct wl_data_source* source, u32 serial);
void wl_data_device_release(WlFuncs* api, struct wl_data_device* obj);

// wl_data_device_manager - enums.
enum wl_data_device_manager_dnd_action {
  WL_DATA_DEVICE_MANAGER_DND_ACTION_NONE = 0,
  WL_DATA_DEVICE_MANAGER_DND_ACTION_COPY = 1,
  WL_DATA_DEVICE_MANAGER_DND_ACTION_MOVE = 2,
  WL_DATA_DEVICE_MANAGER_DND_ACTION_ASK = 4,
};

// wl_data_device_manager - request opcodes.
#define WL_DATA_DEVICE_MANAGER_CREATE_DATA_SOURCE 0
#define WL_DATA_DEVICE_MANAGER_GET_DATA_DEVICE 1

// wl_data_device_manager - utility wrappers.
u32 wl_data_device_manager_get_version(WlFuncs* api, struct wl_data_device_manager* obj);
void wl_data_device_manager_destroy(WlFuncs* api, struct wl_data_device_manager* obj);

// wl_data_device_manager - request wrappers.
struct wl_data_source* wl_data_device_manager_create_data_source(WlFuncs* api, struct wl_data_device_manager* obj);
struct wl_data_device* wl_data_device_manager_get_data_device(WlFuncs* api, struct wl_data_device_manager* obj, struct wl_seat* seat);

// wl_shell - enums.
enum wl_shell_error {
  WL_SHELL_ERROR_ROLE = 0,
};

// wl_shell - request opcodes.
#define WL_SHELL_GET_SHELL_SURFACE 0

// wl_shell - utility wrappers.
u32 wl_shell_get_version(WlFuncs* api, struct wl_shell* obj);
void wl_shell_destroy(WlFuncs* api, struct wl_shell* obj);

// wl_shell - request wrappers.
struct wl_shell_surface* wl_shell_get_shell_surface(WlFuncs* api, struct wl_shell* obj, struct wl_surface* surface);

// wl_shell_surface - enums.
enum wl_shell_surface_resize {
  WL_SHELL_SURFACE_RESIZE_NONE = 0,
  WL_SHELL_SURFACE_RESIZE_TOP = 1,
  WL_SHELL_SURFACE_RESIZE_BOTTOM = 2,
  WL_SHELL_SURFACE_RESIZE_LEFT = 4,
  WL_SHELL_SURFACE_RESIZE_TOP_LEFT = 5,
  WL_SHELL_SURFACE_RESIZE_BOTTOM_LEFT = 6,
  WL_SHELL_SURFACE_RESIZE_RIGHT = 8,
  WL_SHELL_SURFACE_RESIZE_TOP_RIGHT = 9,
  WL_SHELL_SURFACE_RESIZE_BOTTOM_RIGHT = 10,
};
enum wl_shell_surface_transient {
  WL_SHELL_SURFACE_TRANSIENT_INACTIVE = 1,
};
enum wl_shell_surface_fullscreen_method {
  WL_SHELL_SURFACE_FULLSCREEN_METHOD_DEFAULT = 0,
  WL_SHELL_SURFACE_FULLSCREEN_METHOD_SCALE = 1,
  WL_SHELL_SURFACE_FULLSCREEN_METHOD_DRIVER = 2,
  WL_SHELL_SURFACE_FULLSCREEN_METHOD_FILL = 3,
};

// wl_shell_surface - request opcodes.
#define WL_SHELL_SURFACE_PONG 0
#define WL_SHELL_SURFACE_MOVE 1
#define WL_SHELL_SURFACE_RESIZE 2
#define WL_SHELL_SURFACE_SET_TOPLEVEL 3
#define WL_SHELL_SURFACE_SET_TRANSIENT 4
#define WL_SHELL_SURFACE_SET_FULLSCREEN 5
#define WL_SHELL_SURFACE_SET_POPUP 6
#define WL_SHELL_SURFACE_SET_MAXIMIZED 7
#define WL_SHELL_SURFACE_SET_TITLE 8
#define WL_SHELL_SURFACE_SET_CLASS 9

// wl_shell_surface - listener.
struct wl_shell_surface_listener {
  void (*ping)(void* data, struct wl_shell_surface*, u32 serial);
  void (*configure)(void* data, struct wl_shell_surface*, u32 edges, i32 width, i32 height);
  void (*popup_done)(void* data, struct wl_shell_surface*);
};

// wl_shell_surface - utility wrappers.
u32 wl_shell_surface_get_version(WlFuncs* api, struct wl_shell_surface* obj);
void wl_shell_surface_destroy(WlFuncs* api, struct wl_shell_surface* obj);
void wl_shell_surface_add_listener(WlFuncs* api, struct wl_shell_surface* obj, const struct wl_shell_surface_listener* listener, void* data);

// wl_shell_surface - request wrappers.
void wl_shell_surface_pong(WlFuncs* api, struct wl_shell_surface* obj, u32 serial);
void wl_shell_surface_move(WlFuncs* api, struct wl_shell_surface* obj, struct wl_seat* seat, u32 serial);
void wl_shell_surface_resize(WlFuncs* api, struct wl_shell_surface* obj, struct wl_seat* seat, u32 serial, u32 edges);
void wl_shell_surface_set_toplevel(WlFuncs* api, struct wl_shell_surface* obj);
void wl_shell_surface_set_transient(WlFuncs* api, struct wl_shell_surface* obj, struct wl_surface* parent, i32 x, i32 y, u32 flags);
void wl_shell_surface_set_fullscreen(WlFuncs* api, struct wl_shell_surface* obj, u32 method, u32 framerate, struct wl_output* output);
void wl_shell_surface_set_popup(WlFuncs* api, struct wl_shell_surface* obj, struct wl_seat* seat, u32 serial, struct wl_surface* parent, i32 x, i32 y, u32 flags);
void wl_shell_surface_set_maximized(WlFuncs* api, struct wl_shell_surface* obj, struct wl_output* output);
void wl_shell_surface_set_title(WlFuncs* api, struct wl_shell_surface* obj, const char* title);
void wl_shell_surface_set_class(WlFuncs* api, struct wl_shell_surface* obj, const char* class_);

// wl_surface - enums.
enum wl_surface_error {
  WL_SURFACE_ERROR_INVALID_SCALE = 0,
  WL_SURFACE_ERROR_INVALID_TRANSFORM = 1,
  WL_SURFACE_ERROR_INVALID_SIZE = 2,
  WL_SURFACE_ERROR_INVALID_OFFSET = 3,
  WL_SURFACE_ERROR_DEFUNCT_ROLE_OBJECT = 4,
};

// wl_surface - request opcodes.
#define WL_SURFACE_DESTROY 0
#define WL_SURFACE_ATTACH 1
#define WL_SURFACE_DAMAGE 2
#define WL_SURFACE_FRAME 3
#define WL_SURFACE_SET_OPAQUE_REGION 4
#define WL_SURFACE_SET_INPUT_REGION 5
#define WL_SURFACE_COMMIT 6
#define WL_SURFACE_SET_BUFFER_TRANSFORM 7
#define WL_SURFACE_SET_BUFFER_SCALE 8
#define WL_SURFACE_DAMAGE_BUFFER 9
#define WL_SURFACE_OFFSET 10

// wl_surface - listener.
struct wl_surface_listener {
  void (*enter)(void* data, struct wl_surface*, struct wl_output* output);
  void (*leave)(void* data, struct wl_surface*, struct wl_output* output);
  void (*preferred_buffer_scale)(void* data, struct wl_surface*, i32 factor);
  void (*preferred_buffer_transform)(void* data, struct wl_surface*, u32 transform);
};

// wl_surface - utility wrappers.
u32 wl_surface_get_version(WlFuncs* api, struct wl_surface* obj);
void wl_surface_add_listener(WlFuncs* api, struct wl_surface* obj, const struct wl_surface_listener* listener, void* data);

// wl_surface - request wrappers.
void wl_surface_destroy(WlFuncs* api, struct wl_surface* obj);
void wl_surface_attach(WlFuncs* api, struct wl_surface* obj, struct wl_buffer* buffer, i32 x, i32 y);
void wl_surface_damage(WlFuncs* api, struct wl_surface* obj, i32 x, i32 y, i32 width, i32 height);
struct wl_callback* wl_surface_frame(WlFuncs* api, struct wl_surface* obj);
void wl_surface_set_opaque_region(WlFuncs* api, struct wl_surface* obj, struct wl_region* region);
void wl_surface_set_input_region(WlFuncs* api, struct wl_surface* obj, struct wl_region* region);
void wl_surface_commit(WlFuncs* api, struct wl_surface* obj);
void wl_surface_set_buffer_transform(WlFuncs* api, struct wl_surface* obj, i32 transform);
void wl_surface_set_buffer_scale(WlFuncs* api, struct wl_surface* obj, i32 scale);
void wl_surface_damage_buffer(WlFuncs* api, struct wl_surface* obj, i32 x, i32 y, i32 width, i32 height);
void wl_surface_offset(WlFuncs* api, struct wl_surface* obj, i32 x, i32 y);

// wl_seat - enums.
enum wl_seat_capability {
  WL_SEAT_CAPABILITY_POINTER = 1,
  WL_SEAT_CAPABILITY_KEYBOARD = 2,
  WL_SEAT_CAPABILITY_TOUCH = 4,
};
enum wl_seat_error {
  WL_SEAT_ERROR_MISSING_CAPABILITY = 0,
};

// wl_seat - request opcodes.
#define WL_SEAT_GET_POINTER 0
#define WL_SEAT_GET_KEYBOARD 1
#define WL_SEAT_GET_TOUCH 2
#define WL_SEAT_RELEASE 3

// wl_seat - listener.
struct wl_seat_listener {
  void (*capabilities)(void* data, struct wl_seat*, u32 capabilities);
  void (*name)(void* data, struct wl_seat*, const char* name);
};

// wl_seat - utility wrappers.
u32 wl_seat_get_version(WlFuncs* api, struct wl_seat* obj);
void wl_seat_add_listener(WlFuncs* api, struct wl_seat* obj, const struct wl_seat_listener* listener, void* data);

// wl_seat - request wrappers.
struct wl_pointer* wl_seat_get_pointer(WlFuncs* api, struct wl_seat* obj);
struct wl_keyboard* wl_seat_get_keyboard(WlFuncs* api, struct wl_seat* obj);
struct wl_touch* wl_seat_get_touch(WlFuncs* api, struct wl_seat* obj);
void wl_seat_release(WlFuncs* api, struct wl_seat* obj);

// wl_pointer - enums.
enum wl_pointer_error {
  WL_POINTER_ERROR_ROLE = 0,
};
enum wl_pointer_button_state {
  WL_POINTER_BUTTON_STATE_RELEASED = 0,
  WL_POINTER_BUTTON_STATE_PRESSED = 1,
};
enum wl_pointer_axis {
  WL_POINTER_AXIS_VERTICAL_SCROLL = 0,
  WL_POINTER_AXIS_HORIZONTAL_SCROLL = 1,
};
enum wl_pointer_axis_source {
  WL_POINTER_AXIS_SOURCE_WHEEL = 0,
  WL_POINTER_AXIS_SOURCE_FINGER = 1,
  WL_POINTER_AXIS_SOURCE_CONTINUOUS = 2,
  WL_POINTER_AXIS_SOURCE_WHEEL_TILT = 3,
};
enum wl_pointer_axis_relative_direction {
  WL_POINTER_AXIS_RELATIVE_DIRECTION_IDENTICAL = 0,
  WL_POINTER_AXIS_RELATIVE_DIRECTION_INVERTED = 1,
};

// wl_pointer - request opcodes.
#define WL_POINTER_SET_CURSOR 0
#define WL_POINTER_RELEASE 1

// wl_pointer - listener.
struct wl_pointer_listener {
  void (*enter)(void* data, struct wl_pointer*, u32 serial, struct wl_surface* surface, i32 surface_x, i32 surface_y);
  void (*leave)(void* data, struct wl_pointer*, u32 serial, struct wl_surface* surface);
  void (*motion)(void* data, struct wl_pointer*, u32 time, i32 surface_x, i32 surface_y);
  void (*button)(void* data, struct wl_pointer*, u32 serial, u32 time, u32 button, u32 state);
  void (*axis)(void* data, struct wl_pointer*, u32 time, u32 axis, i32 value);
  void (*frame)(void* data, struct wl_pointer*);
  void (*axis_source)(void* data, struct wl_pointer*, u32 axis_source);
  void (*axis_stop)(void* data, struct wl_pointer*, u32 time, u32 axis);
  void (*axis_discrete)(void* data, struct wl_pointer*, u32 axis, i32 discrete);
  void (*axis_value120)(void* data, struct wl_pointer*, u32 axis, i32 value120);
  void (*axis_relative_direction)(void* data, struct wl_pointer*, u32 axis, u32 direction);
};

// wl_pointer - utility wrappers.
u32 wl_pointer_get_version(WlFuncs* api, struct wl_pointer* obj);
void wl_pointer_add_listener(WlFuncs* api, struct wl_pointer* obj, const struct wl_pointer_listener* listener, void* data);

// wl_pointer - request wrappers.
void wl_pointer_set_cursor(WlFuncs* api, struct wl_pointer* obj, u32 serial, struct wl_surface* surface, i32 hotspot_x, i32 hotspot_y);
void wl_pointer_release(WlFuncs* api, struct wl_pointer* obj);

// wl_keyboard - enums.
enum wl_keyboard_keymap_format {
  WL_KEYBOARD_KEYMAP_FORMAT_NO_KEYMAP = 0,
  WL_KEYBOARD_KEYMAP_FORMAT_XKB_V1 = 1,
};
enum wl_keyboard_key_state {
  WL_KEYBOARD_KEY_STATE_RELEASED = 0,
  WL_KEYBOARD_KEY_STATE_PRESSED = 1,
  WL_KEYBOARD_KEY_STATE_REPEATED = 2,
};

// wl_keyboard - request opcodes.
#define WL_KEYBOARD_RELEASE 0

// wl_keyboard - listener.
struct wl_keyboard_listener {
  void (*keymap)(void* data, struct wl_keyboard*, u32 format, i32 fd, u32 size);
  void (*enter)(void* data, struct wl_keyboard*, u32 serial, struct wl_surface* surface, struct wl_array* keys);
  void (*leave)(void* data, struct wl_keyboard*, u32 serial, struct wl_surface* surface);
  void (*key)(void* data, struct wl_keyboard*, u32 serial, u32 time, u32 key, u32 state);
  void (*modifiers)(void* data, struct wl_keyboard*, u32 serial, u32 mods_depressed, u32 mods_latched, u32 mods_locked, u32 group);
  void (*repeat_info)(void* data, struct wl_keyboard*, i32 rate, i32 delay);
};

// wl_keyboard - utility wrappers.
u32 wl_keyboard_get_version(WlFuncs* api, struct wl_keyboard* obj);
void wl_keyboard_add_listener(WlFuncs* api, struct wl_keyboard* obj, const struct wl_keyboard_listener* listener, void* data);

// wl_keyboard - request wrappers.
void wl_keyboard_release(WlFuncs* api, struct wl_keyboard* obj);

// wl_touch - request opcodes.
#define WL_TOUCH_RELEASE 0

// wl_touch - listener.
struct wl_touch_listener {
  void (*down)(void* data, struct wl_touch*, u32 serial, u32 time, struct wl_surface* surface, i32 id, i32 x, i32 y);
  void (*up)(void* data, struct wl_touch*, u32 serial, u32 time, i32 id);
  void (*motion)(void* data, struct wl_touch*, u32 time, i32 id, i32 x, i32 y);
  void (*frame)(void* data, struct wl_touch*);
  void (*cancel)(void* data, struct wl_touch*);
  void (*shape)(void* data, struct wl_touch*, i32 id, i32 major, i32 minor);
  void (*orientation)(void* data, struct wl_touch*, i32 id, i32 orientation);
};

// wl_touch - utility wrappers.
u32 wl_touch_get_version(WlFuncs* api, struct wl_touch* obj);
void wl_touch_add_listener(WlFuncs* api, struct wl_touch* obj, const struct wl_touch_listener* listener, void* data);

// wl_touch - request wrappers.
void wl_touch_release(WlFuncs* api, struct wl_touch* obj);

// wl_output - enums.
enum wl_output_subpixel {
  WL_OUTPUT_SUBPIXEL_UNKNOWN = 0,
  WL_OUTPUT_SUBPIXEL_NONE = 1,
  WL_OUTPUT_SUBPIXEL_HORIZONTAL_RGB = 2,
  WL_OUTPUT_SUBPIXEL_HORIZONTAL_BGR = 3,
  WL_OUTPUT_SUBPIXEL_VERTICAL_RGB = 4,
  WL_OUTPUT_SUBPIXEL_VERTICAL_BGR = 5,
};
enum wl_output_transform {
  WL_OUTPUT_TRANSFORM_NORMAL = 0,
  WL_OUTPUT_TRANSFORM_90 = 1,
  WL_OUTPUT_TRANSFORM_180 = 2,
  WL_OUTPUT_TRANSFORM_270 = 3,
  WL_OUTPUT_TRANSFORM_FLIPPED = 4,
  WL_OUTPUT_TRANSFORM_FLIPPED_90 = 5,
  WL_OUTPUT_TRANSFORM_FLIPPED_180 = 6,
  WL_OUTPUT_TRANSFORM_FLIPPED_270 = 7,
};
enum wl_output_mode {
  WL_OUTPUT_MODE_CURRENT = 1,
  WL_OUTPUT_MODE_PREFERRED = 2,
};

// wl_output - request opcodes.
#define WL_OUTPUT_RELEASE 0

// wl_output - listener.
struct wl_output_listener {
  void (*geometry)(void* data, struct wl_output*, i32 x, i32 y, i32 physical_width, i32 physical_height, i32 subpixel, const char* make, const char* model, i32 transform);
  void (*mode)(void* data, struct wl_output*, u32 flags, i32 width, i32 height, i32 refresh);
  void (*done)(void* data, struct wl_output*);
  void (*scale)(void* data, struct wl_output*, i32 factor);
  void (*name)(void* data, struct wl_output*, const char* name);
  void (*description)(void* data, struct wl_output*, const char* description);
};

// wl_output - utility wrappers.
u32 wl_output_get_version(WlFuncs* api, struct wl_output* obj);
void wl_output_add_listener(WlFuncs* api, struct wl_output* obj, const struct wl_output_listener* listener, void* data);

// wl_output - request wrappers.
void wl_output_release(WlFuncs* api, struct wl_output* obj);

// wl_region - request opcodes.
#define WL_REGION_DESTROY 0
#define WL_REGION_ADD 1
#define WL_REGION_SUBTRACT 2

// wl_region - utility wrappers.
u32 wl_region_get_version(WlFuncs* api, struct wl_region* obj);

// wl_region - request wrappers.
void wl_region_destroy(WlFuncs* api, struct wl_region* obj);
void wl_region_add(WlFuncs* api, struct wl_region* obj, i32 x, i32 y, i32 width, i32 height);
void wl_region_subtract(WlFuncs* api, struct wl_region* obj, i32 x, i32 y, i32 width, i32 height);

// wl_subcompositor - enums.
enum wl_subcompositor_error {
  WL_SUBCOMPOSITOR_ERROR_BAD_SURFACE = 0,
  WL_SUBCOMPOSITOR_ERROR_BAD_PARENT = 1,
};

// wl_subcompositor - request opcodes.
#define WL_SUBCOMPOSITOR_DESTROY 0
#define WL_SUBCOMPOSITOR_GET_SUBSURFACE 1

// wl_subcompositor - utility wrappers.
u32 wl_subcompositor_get_version(WlFuncs* api, struct wl_subcompositor* obj);

// wl_subcompositor - request wrappers.
void wl_subcompositor_destroy(WlFuncs* api, struct wl_subcompositor* obj);
struct wl_subsurface* wl_subcompositor_get_subsurface(WlFuncs* api, struct wl_subcompositor* obj, struct wl_surface* surface, struct wl_surface* parent);

// wl_subsurface - enums.
enum wl_subsurface_error {
  WL_SUBSURFACE_ERROR_BAD_SURFACE = 0,
};

// wl_subsurface - request opcodes.
#define WL_SUBSURFACE_DESTROY 0
#define WL_SUBSURFACE_SET_POSITION 1
#define WL_SUBSURFACE_PLACE_ABOVE 2
#define WL_SUBSURFACE_PLACE_BELOW 3
#define WL_SUBSURFACE_SET_SYNC 4
#define WL_SUBSURFACE_SET_DESYNC 5

// wl_subsurface - utility wrappers.
u32 wl_subsurface_get_version(WlFuncs* api, struct wl_subsurface* obj);

// wl_subsurface - request wrappers.
void wl_subsurface_destroy(WlFuncs* api, struct wl_subsurface* obj);
void wl_subsurface_set_position(WlFuncs* api, struct wl_subsurface* obj, i32 x, i32 y);
void wl_subsurface_place_above(WlFuncs* api, struct wl_subsurface* obj, struct wl_surface* sibling);
void wl_subsurface_place_below(WlFuncs* api, struct wl_subsurface* obj, struct wl_surface* sibling);
void wl_subsurface_set_sync(WlFuncs* api, struct wl_subsurface* obj);
void wl_subsurface_set_desync(WlFuncs* api, struct wl_subsurface* obj);

// wl_fixes - request opcodes.
#define WL_FIXES_DESTROY 0
#define WL_FIXES_DESTROY_REGISTRY 1

// wl_fixes - utility wrappers.
u32 wl_fixes_get_version(WlFuncs* api, struct wl_fixes* obj);

// wl_fixes - request wrappers.
void wl_fixes_destroy(WlFuncs* api, struct wl_fixes* obj);
void wl_fixes_destroy_registry(WlFuncs* api, struct wl_fixes* obj, struct wl_registry* registry);

// xdg_wm_base - enums.
enum xdg_wm_base_error {
  XDG_WM_BASE_ERROR_ROLE = 0,
  XDG_WM_BASE_ERROR_DEFUNCT_SURFACES = 1,
  XDG_WM_BASE_ERROR_NOT_THE_TOPMOST_POPUP = 2,
  XDG_WM_BASE_ERROR_INVALID_POPUP_PARENT = 3,
  XDG_WM_BASE_ERROR_INVALID_SURFACE_STATE = 4,
  XDG_WM_BASE_ERROR_INVALID_POSITIONER = 5,
  XDG_WM_BASE_ERROR_UNRESPONSIVE = 6,
};

// xdg_wm_base - request opcodes.
#define XDG_WM_BASE_DESTROY 0
#define XDG_WM_BASE_CREATE_POSITIONER 1
#define XDG_WM_BASE_GET_XDG_SURFACE 2
#define XDG_WM_BASE_PONG 3

// xdg_wm_base - listener.
struct xdg_wm_base_listener {
  void (*ping)(void* data, struct xdg_wm_base*, u32 serial);
};

// xdg_wm_base - utility wrappers.
u32 xdg_wm_base_get_version(WlFuncs* api, struct xdg_wm_base* obj);
void xdg_wm_base_add_listener(WlFuncs* api, struct xdg_wm_base* obj, const struct xdg_wm_base_listener* listener, void* data);

// xdg_wm_base - request wrappers.
void xdg_wm_base_destroy(WlFuncs* api, struct xdg_wm_base* obj);
struct xdg_positioner* xdg_wm_base_create_positioner(WlFuncs* api, struct xdg_wm_base* obj);
struct xdg_surface* xdg_wm_base_get_xdg_surface(WlFuncs* api, struct xdg_wm_base* obj, struct wl_surface* surface);
void xdg_wm_base_pong(WlFuncs* api, struct xdg_wm_base* obj, u32 serial);

// xdg_positioner - enums.
enum xdg_positioner_error {
  XDG_POSITIONER_ERROR_INVALID_INPUT = 0,
};
enum xdg_positioner_anchor {
  XDG_POSITIONER_ANCHOR_NONE = 0,
  XDG_POSITIONER_ANCHOR_TOP = 1,
  XDG_POSITIONER_ANCHOR_BOTTOM = 2,
  XDG_POSITIONER_ANCHOR_LEFT = 3,
  XDG_POSITIONER_ANCHOR_RIGHT = 4,
  XDG_POSITIONER_ANCHOR_TOP_LEFT = 5,
  XDG_POSITIONER_ANCHOR_BOTTOM_LEFT = 6,
  XDG_POSITIONER_ANCHOR_TOP_RIGHT = 7,
  XDG_POSITIONER_ANCHOR_BOTTOM_RIGHT = 8,
};
enum xdg_positioner_gravity {
  XDG_POSITIONER_GRAVITY_NONE = 0,
  XDG_POSITIONER_GRAVITY_TOP = 1,
  XDG_POSITIONER_GRAVITY_BOTTOM = 2,
  XDG_POSITIONER_GRAVITY_LEFT = 3,
  XDG_POSITIONER_GRAVITY_RIGHT = 4,
  XDG_POSITIONER_GRAVITY_TOP_LEFT = 5,
  XDG_POSITIONER_GRAVITY_BOTTOM_LEFT = 6,
  XDG_POSITIONER_GRAVITY_TOP_RIGHT = 7,
  XDG_POSITIONER_GRAVITY_BOTTOM_RIGHT = 8,
};
enum xdg_positioner_constraint_adjustment {
  XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_NONE = 0,
  XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_SLIDE_X = 1,
  XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_SLIDE_Y = 2,
  XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_FLIP_X = 4,
  XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_FLIP_Y = 8,
  XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_RESIZE_X = 16,
  XDG_POSITIONER_CONSTRAINT_ADJUSTMENT_RESIZE_Y = 32,
};

// xdg_positioner - request opcodes.
#define XDG_POSITIONER_DESTROY 0
#define XDG_POSITIONER_SET_SIZE 1
#define XDG_POSITIONER_SET_ANCHOR_RECT 2
#define XDG_POSITIONER_SET_ANCHOR 3
#define XDG_POSITIONER_SET_GRAVITY 4
#define XDG_POSITIONER_SET_CONSTRAINT_ADJUSTMENT 5
#define XDG_POSITIONER_SET_OFFSET 6
#define XDG_POSITIONER_SET_REACTIVE 7
#define XDG_POSITIONER_SET_PARENT_SIZE 8
#define XDG_POSITIONER_SET_PARENT_CONFIGURE 9

// xdg_positioner - utility wrappers.
u32 xdg_positioner_get_version(WlFuncs* api, struct xdg_positioner* obj);

// xdg_positioner - request wrappers.
void xdg_positioner_destroy(WlFuncs* api, struct xdg_positioner* obj);
void xdg_positioner_set_size(WlFuncs* api, struct xdg_positioner* obj, i32 width, i32 height);
void xdg_positioner_set_anchor_rect(WlFuncs* api, struct xdg_positioner* obj, i32 x, i32 y, i32 width, i32 height);
void xdg_positioner_set_anchor(WlFuncs* api, struct xdg_positioner* obj, u32 anchor);
void xdg_positioner_set_gravity(WlFuncs* api, struct xdg_positioner* obj, u32 gravity);
void xdg_positioner_set_constraint_adjustment(WlFuncs* api, struct xdg_positioner* obj, u32 constraint_adjustment);
void xdg_positioner_set_offset(WlFuncs* api, struct xdg_positioner* obj, i32 x, i32 y);
void xdg_positioner_set_reactive(WlFuncs* api, struct xdg_positioner* obj);
void xdg_positioner_set_parent_size(WlFuncs* api, struct xdg_positioner* obj, i32 parent_width, i32 parent_height);
void xdg_positioner_set_parent_configure(WlFuncs* api, struct xdg_positioner* obj, u32 serial);

// xdg_surface - enums.
enum xdg_surface_error {
  XDG_SURFACE_ERROR_NOT_CONSTRUCTED = 1,
  XDG_SURFACE_ERROR_ALREADY_CONSTRUCTED = 2,
  XDG_SURFACE_ERROR_UNCONFIGURED_BUFFER = 3,
  XDG_SURFACE_ERROR_INVALID_SERIAL = 4,
  XDG_SURFACE_ERROR_INVALID_SIZE = 5,
  XDG_SURFACE_ERROR_DEFUNCT_ROLE_OBJECT = 6,
};

// xdg_surface - request opcodes.
#define XDG_SURFACE_DESTROY 0
#define XDG_SURFACE_GET_TOPLEVEL 1
#define XDG_SURFACE_GET_POPUP 2
#define XDG_SURFACE_SET_WINDOW_GEOMETRY 3
#define XDG_SURFACE_ACK_CONFIGURE 4

// xdg_surface - listener.
struct xdg_surface_listener {
  void (*configure)(void* data, struct xdg_surface*, u32 serial);
};

// xdg_surface - utility wrappers.
u32 xdg_surface_get_version(WlFuncs* api, struct xdg_surface* obj);
void xdg_surface_add_listener(WlFuncs* api, struct xdg_surface* obj, const struct xdg_surface_listener* listener, void* data);

// xdg_surface - request wrappers.
void xdg_surface_destroy(WlFuncs* api, struct xdg_surface* obj);
struct xdg_toplevel* xdg_surface_get_toplevel(WlFuncs* api, struct xdg_surface* obj);
struct xdg_popup* xdg_surface_get_popup(WlFuncs* api, struct xdg_surface* obj, struct xdg_surface* parent, struct xdg_positioner* positioner);
void xdg_surface_set_window_geometry(WlFuncs* api, struct xdg_surface* obj, i32 x, i32 y, i32 width, i32 height);
void xdg_surface_ack_configure(WlFuncs* api, struct xdg_surface* obj, u32 serial);

// xdg_toplevel - enums.
enum xdg_toplevel_error {
  XDG_TOPLEVEL_ERROR_INVALID_RESIZE_EDGE = 0,
  XDG_TOPLEVEL_ERROR_INVALID_PARENT = 1,
  XDG_TOPLEVEL_ERROR_INVALID_SIZE = 2,
};
enum xdg_toplevel_resize_edge {
  XDG_TOPLEVEL_RESIZE_EDGE_NONE = 0,
  XDG_TOPLEVEL_RESIZE_EDGE_TOP = 1,
  XDG_TOPLEVEL_RESIZE_EDGE_BOTTOM = 2,
  XDG_TOPLEVEL_RESIZE_EDGE_LEFT = 4,
  XDG_TOPLEVEL_RESIZE_EDGE_TOP_LEFT = 5,
  XDG_TOPLEVEL_RESIZE_EDGE_BOTTOM_LEFT = 6,
  XDG_TOPLEVEL_RESIZE_EDGE_RIGHT = 8,
  XDG_TOPLEVEL_RESIZE_EDGE_TOP_RIGHT = 9,
  XDG_TOPLEVEL_RESIZE_EDGE_BOTTOM_RIGHT = 10,
};
enum xdg_toplevel_state {
  XDG_TOPLEVEL_STATE_MAXIMIZED = 1,
  XDG_TOPLEVEL_STATE_FULLSCREEN = 2,
  XDG_TOPLEVEL_STATE_RESIZING = 3,
  XDG_TOPLEVEL_STATE_ACTIVATED = 4,
  XDG_TOPLEVEL_STATE_TILED_LEFT = 5,
  XDG_TOPLEVEL_STATE_TILED_RIGHT = 6,
  XDG_TOPLEVEL_STATE_TILED_TOP = 7,
  XDG_TOPLEVEL_STATE_TILED_BOTTOM = 8,
  XDG_TOPLEVEL_STATE_SUSPENDED = 9,
  XDG_TOPLEVEL_STATE_CONSTRAINED_LEFT = 10,
  XDG_TOPLEVEL_STATE_CONSTRAINED_RIGHT = 11,
  XDG_TOPLEVEL_STATE_CONSTRAINED_TOP = 12,
  XDG_TOPLEVEL_STATE_CONSTRAINED_BOTTOM = 13,
};
enum xdg_toplevel_wm_capabilities {
  XDG_TOPLEVEL_WM_CAPABILITIES_WINDOW_MENU = 1,
  XDG_TOPLEVEL_WM_CAPABILITIES_MAXIMIZE = 2,
  XDG_TOPLEVEL_WM_CAPABILITIES_FULLSCREEN = 3,
  XDG_TOPLEVEL_WM_CAPABILITIES_MINIMIZE = 4,
};

// xdg_toplevel - request opcodes.
#define XDG_TOPLEVEL_DESTROY 0
#define XDG_TOPLEVEL_SET_PARENT 1
#define XDG_TOPLEVEL_SET_TITLE 2
#define XDG_TOPLEVEL_SET_APP_ID 3
#define XDG_TOPLEVEL_SHOW_WINDOW_MENU 4
#define XDG_TOPLEVEL_MOVE 5
#define XDG_TOPLEVEL_RESIZE 6
#define XDG_TOPLEVEL_SET_MAX_SIZE 7
#define XDG_TOPLEVEL_SET_MIN_SIZE 8
#define XDG_TOPLEVEL_SET_MAXIMIZED 9
#define XDG_TOPLEVEL_UNSET_MAXIMIZED 10
#define XDG_TOPLEVEL_SET_FULLSCREEN 11
#define XDG_TOPLEVEL_UNSET_FULLSCREEN 12
#define XDG_TOPLEVEL_SET_MINIMIZED 13

// xdg_toplevel - listener.
struct xdg_toplevel_listener {
  void (*configure)(void* data, struct xdg_toplevel*, i32 width, i32 height, struct wl_array* states);
  void (*close)(void* data, struct xdg_toplevel*);
  void (*configure_bounds)(void* data, struct xdg_toplevel*, i32 width, i32 height);
  void (*wm_capabilities)(void* data, struct xdg_toplevel*, struct wl_array* capabilities);
};

// xdg_toplevel - utility wrappers.
u32 xdg_toplevel_get_version(WlFuncs* api, struct xdg_toplevel* obj);
void xdg_toplevel_add_listener(WlFuncs* api, struct xdg_toplevel* obj, const struct xdg_toplevel_listener* listener, void* data);

// xdg_toplevel - request wrappers.
void xdg_toplevel_destroy(WlFuncs* api, struct xdg_toplevel* obj);
void xdg_toplevel_set_parent(WlFuncs* api, struct xdg_toplevel* obj, struct xdg_toplevel* parent);
void xdg_toplevel_set_title(WlFuncs* api, struct xdg_toplevel* obj, const char* title);
void xdg_toplevel_set_app_id(WlFuncs* api, struct xdg_toplevel* obj, const char* app_id);
void xdg_toplevel_show_window_menu(WlFuncs* api, struct xdg_toplevel* obj, struct wl_seat* seat, u32 serial, i32 x, i32 y);
void xdg_toplevel_move(WlFuncs* api, struct xdg_toplevel* obj, struct wl_seat* seat, u32 serial);
void xdg_toplevel_resize(WlFuncs* api, struct xdg_toplevel* obj, struct wl_seat* seat, u32 serial, u32 edges);
void xdg_toplevel_set_max_size(WlFuncs* api, struct xdg_toplevel* obj, i32 width, i32 height);
void xdg_toplevel_set_min_size(WlFuncs* api, struct xdg_toplevel* obj, i32 width, i32 height);
void xdg_toplevel_set_maximized(WlFuncs* api, struct xdg_toplevel* obj);
void xdg_toplevel_unset_maximized(WlFuncs* api, struct xdg_toplevel* obj);
void xdg_toplevel_set_fullscreen(WlFuncs* api, struct xdg_toplevel* obj, struct wl_output* output);
void xdg_toplevel_unset_fullscreen(WlFuncs* api, struct xdg_toplevel* obj);
void xdg_toplevel_set_minimized(WlFuncs* api, struct xdg_toplevel* obj);

// xdg_popup - enums.
enum xdg_popup_error {
  XDG_POPUP_ERROR_INVALID_GRAB = 0,
};

// xdg_popup - request opcodes.
#define XDG_POPUP_DESTROY 0
#define XDG_POPUP_GRAB 1
#define XDG_POPUP_REPOSITION 2

// xdg_popup - listener.
struct xdg_popup_listener {
  void (*configure)(void* data, struct xdg_popup*, i32 x, i32 y, i32 width, i32 height);
  void (*popup_done)(void* data, struct xdg_popup*);
  void (*repositioned)(void* data, struct xdg_popup*, u32 token);
};

// xdg_popup - utility wrappers.
u32 xdg_popup_get_version(WlFuncs* api, struct xdg_popup* obj);
void xdg_popup_add_listener(WlFuncs* api, struct xdg_popup* obj, const struct xdg_popup_listener* listener, void* data);

// xdg_popup - request wrappers.
void xdg_popup_destroy(WlFuncs* api, struct xdg_popup* obj);
void xdg_popup_grab(WlFuncs* api, struct xdg_popup* obj, struct wl_seat* seat, u32 serial);
void xdg_popup_reposition(WlFuncs* api, struct xdg_popup* obj, struct xdg_positioner* positioner, u32 token);

// clang-format on
