// clang-format off
// Generated by 'wlgen' from '/nix/store/vv8mrvh447wpapvim5adif1izf57f3sw-wayland-scanner-1.24.0/share/wayland/wayland.xml' from '/nix/store/1hjwhmhrv1nshdm4n674rrllva5khv5d-wayland-protocols-1.45/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml'.

#include "wayland.h"
#include "core/dynlib.h"
#include "core/string.h"

bool wlLoad(const DynLib* lib, WlFuncs* out) {
  out->display_connect          = dynlib_symbol(lib, string_lit("wl_display_connect"));
  out->display_disconnect       = dynlib_symbol(lib, string_lit("wl_display_disconnect"));
  out->display_dispatch         = dynlib_symbol(lib, string_lit("wl_display_dispatch"));
  out->display_dispatch_pending = dynlib_symbol(lib, string_lit("wl_display_dispatch_pending"));
  out->display_roundtrip        = dynlib_symbol(lib, string_lit("wl_display_roundtrip"));
  out->display_flush            = dynlib_symbol(lib, string_lit("wl_display_flush"));
  out->display_get_registry     = dynlib_symbol(lib, string_lit("wl_display_get_registry"));
  out->proxy_add_listener       = dynlib_symbol(lib, string_lit("wl_proxy_add_listener"));
  out->proxy_marshal_flags      = dynlib_symbol(lib, string_lit("wl_proxy_marshal_flags"));
  out->proxy_get_version        = dynlib_symbol(lib, string_lit("wl_proxy_get_version"));
  out->proxy_destroy            = dynlib_symbol(lib, string_lit("wl_proxy_destroy"));
  return out->display_connect && out->display_disconnect &&
         out->display_dispatch && out->display_dispatch_pending &&
         out->display_roundtrip && out->display_flush &&
         out->display_get_registry && out->proxy_add_listener &&
         out->proxy_marshal_flags && out->proxy_get_version &&
         out->proxy_destroy;
}

void* wlRegistryBind(
    WlFuncs* api, struct wl_registry* registry, u32 name, u32 version,
    const struct wl_interface* iface, u32 maxVersion) {
  const u32 bindVersion = version < maxVersion ? version : maxVersion;
  return api->proxy_marshal_flags(
      (struct wl_proxy*)registry, WL_REGISTRY_BIND, iface, bindVersion, 0,
      name, iface->name, bindVersion, null);
}

// Minimal wl_interface definitions: only name and version are required
// at runtime for proxy_marshal_flags calls.

const struct wl_interface wl_display_interface = {"wl_display", 1, 0, null, 0, null};
const struct wl_interface wl_registry_interface = {"wl_registry", 1, 0, null, 0, null};
const struct wl_interface wl_callback_interface = {"wl_callback", 1, 0, null, 0, null};
const struct wl_interface wl_compositor_interface = {"wl_compositor", 6, 0, null, 0, null};
const struct wl_interface wl_shm_pool_interface = {"wl_shm_pool", 2, 0, null, 0, null};
const struct wl_interface wl_shm_interface = {"wl_shm", 2, 0, null, 0, null};
const struct wl_interface wl_buffer_interface = {"wl_buffer", 1, 0, null, 0, null};
const struct wl_interface wl_data_offer_interface = {"wl_data_offer", 3, 0, null, 0, null};
const struct wl_interface wl_data_source_interface = {"wl_data_source", 3, 0, null, 0, null};
const struct wl_interface wl_data_device_interface = {"wl_data_device", 3, 0, null, 0, null};
const struct wl_interface wl_data_device_manager_interface = {"wl_data_device_manager", 3, 0, null, 0, null};
const struct wl_interface wl_shell_interface = {"wl_shell", 1, 0, null, 0, null};
const struct wl_interface wl_shell_surface_interface = {"wl_shell_surface", 1, 0, null, 0, null};
const struct wl_interface wl_surface_interface = {"wl_surface", 6, 0, null, 0, null};
const struct wl_interface wl_seat_interface = {"wl_seat", 10, 0, null, 0, null};
const struct wl_interface wl_pointer_interface = {"wl_pointer", 10, 0, null, 0, null};
const struct wl_interface wl_keyboard_interface = {"wl_keyboard", 10, 0, null, 0, null};
const struct wl_interface wl_touch_interface = {"wl_touch", 10, 0, null, 0, null};
const struct wl_interface wl_output_interface = {"wl_output", 4, 0, null, 0, null};
const struct wl_interface wl_region_interface = {"wl_region", 1, 0, null, 0, null};
const struct wl_interface wl_subcompositor_interface = {"wl_subcompositor", 1, 0, null, 0, null};
const struct wl_interface wl_subsurface_interface = {"wl_subsurface", 1, 0, null, 0, null};
const struct wl_interface wl_fixes_interface = {"wl_fixes", 1, 0, null, 0, null};
const struct wl_interface xdg_wm_base_interface = {"xdg_wm_base", 7, 0, null, 0, null};
const struct wl_interface xdg_positioner_interface = {"xdg_positioner", 7, 0, null, 0, null};
const struct wl_interface xdg_surface_interface = {"xdg_surface", 7, 0, null, 0, null};
const struct wl_interface xdg_toplevel_interface = {"xdg_toplevel", 7, 0, null, 0, null};
const struct wl_interface xdg_popup_interface = {"xdg_popup", 7, 0, null, 0, null};

// wl_display - utility wrappers.
u32 wl_display_get_version(WlFuncs* api, struct wl_display* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}
void wl_display_destroy(WlFuncs* api, struct wl_display* obj) {
  api->proxy_destroy((struct wl_proxy*)obj);
}
void wl_display_add_listener(WlFuncs* api, struct wl_display* obj, const struct wl_display_listener* listener, void* data) {
  api->proxy_add_listener((struct wl_proxy*)obj, (void(**)(void))listener, data);
}

// wl_display - request wrappers.
struct wl_callback* wl_display_sync(WlFuncs* api, struct wl_display* obj) {
  return api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_DISPLAY_SYNC, &wl_callback_interface,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, null);
}
struct wl_registry* wl_display_get_registry(WlFuncs* api, struct wl_display* obj) {
  return api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_DISPLAY_GET_REGISTRY, &wl_registry_interface,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, null);
}

// wl_registry - utility wrappers.
u32 wl_registry_get_version(WlFuncs* api, struct wl_registry* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}
void wl_registry_destroy(WlFuncs* api, struct wl_registry* obj) {
  api->proxy_destroy((struct wl_proxy*)obj);
}
void wl_registry_add_listener(WlFuncs* api, struct wl_registry* obj, const struct wl_registry_listener* listener, void* data) {
  api->proxy_add_listener((struct wl_proxy*)obj, (void(**)(void))listener, data);
}

// wl_callback - utility wrappers.
u32 wl_callback_get_version(WlFuncs* api, struct wl_callback* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}
void wl_callback_destroy(WlFuncs* api, struct wl_callback* obj) {
  api->proxy_destroy((struct wl_proxy*)obj);
}
void wl_callback_add_listener(WlFuncs* api, struct wl_callback* obj, const struct wl_callback_listener* listener, void* data) {
  api->proxy_add_listener((struct wl_proxy*)obj, (void(**)(void))listener, data);
}

// wl_compositor - utility wrappers.
u32 wl_compositor_get_version(WlFuncs* api, struct wl_compositor* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}
void wl_compositor_destroy(WlFuncs* api, struct wl_compositor* obj) {
  api->proxy_destroy((struct wl_proxy*)obj);
}

// wl_compositor - request wrappers.
struct wl_surface* wl_compositor_create_surface(WlFuncs* api, struct wl_compositor* obj) {
  return api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_COMPOSITOR_CREATE_SURFACE, &wl_surface_interface,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, null);
}
struct wl_region* wl_compositor_create_region(WlFuncs* api, struct wl_compositor* obj) {
  return api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_COMPOSITOR_CREATE_REGION, &wl_region_interface,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, null);
}

// wl_shm_pool - utility wrappers.
u32 wl_shm_pool_get_version(WlFuncs* api, struct wl_shm_pool* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}

// wl_shm_pool - request wrappers.
struct wl_buffer* wl_shm_pool_create_buffer(WlFuncs* api, struct wl_shm_pool* obj, i32 offset, i32 width, i32 height, i32 stride, u32 format) {
  return api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SHM_POOL_CREATE_BUFFER, &wl_buffer_interface,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, null, offset, width, height, stride, format);
}
void wl_shm_pool_destroy(WlFuncs* api, struct wl_shm_pool* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SHM_POOL_DESTROY, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      WL_MARSHAL_FLAG_DESTROY);
}
void wl_shm_pool_resize(WlFuncs* api, struct wl_shm_pool* obj, i32 size) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SHM_POOL_RESIZE, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, size);
}

// wl_shm - utility wrappers.
u32 wl_shm_get_version(WlFuncs* api, struct wl_shm* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}
void wl_shm_add_listener(WlFuncs* api, struct wl_shm* obj, const struct wl_shm_listener* listener, void* data) {
  api->proxy_add_listener((struct wl_proxy*)obj, (void(**)(void))listener, data);
}

// wl_shm - request wrappers.
struct wl_shm_pool* wl_shm_create_pool(WlFuncs* api, struct wl_shm* obj, i32 fd, i32 size) {
  return api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SHM_CREATE_POOL, &wl_shm_pool_interface,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, null, fd, size);
}
void wl_shm_release(WlFuncs* api, struct wl_shm* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SHM_RELEASE, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      WL_MARSHAL_FLAG_DESTROY);
}

// wl_buffer - utility wrappers.
u32 wl_buffer_get_version(WlFuncs* api, struct wl_buffer* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}
void wl_buffer_add_listener(WlFuncs* api, struct wl_buffer* obj, const struct wl_buffer_listener* listener, void* data) {
  api->proxy_add_listener((struct wl_proxy*)obj, (void(**)(void))listener, data);
}

// wl_buffer - request wrappers.
void wl_buffer_destroy(WlFuncs* api, struct wl_buffer* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_BUFFER_DESTROY, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      WL_MARSHAL_FLAG_DESTROY);
}

// wl_data_offer - utility wrappers.
u32 wl_data_offer_get_version(WlFuncs* api, struct wl_data_offer* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}
void wl_data_offer_add_listener(WlFuncs* api, struct wl_data_offer* obj, const struct wl_data_offer_listener* listener, void* data) {
  api->proxy_add_listener((struct wl_proxy*)obj, (void(**)(void))listener, data);
}

// wl_data_offer - request wrappers.
void wl_data_offer_accept(WlFuncs* api, struct wl_data_offer* obj, u32 serial, const char* mime_type) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_DATA_OFFER_ACCEPT, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, serial, mime_type);
}
void wl_data_offer_receive(WlFuncs* api, struct wl_data_offer* obj, const char* mime_type, i32 fd) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_DATA_OFFER_RECEIVE, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, mime_type, fd);
}
void wl_data_offer_destroy(WlFuncs* api, struct wl_data_offer* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_DATA_OFFER_DESTROY, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      WL_MARSHAL_FLAG_DESTROY);
}
void wl_data_offer_finish(WlFuncs* api, struct wl_data_offer* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_DATA_OFFER_FINISH, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0);
}
void wl_data_offer_set_actions(WlFuncs* api, struct wl_data_offer* obj, u32 dnd_actions, u32 preferred_action) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_DATA_OFFER_SET_ACTIONS, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, dnd_actions, preferred_action);
}

// wl_data_source - utility wrappers.
u32 wl_data_source_get_version(WlFuncs* api, struct wl_data_source* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}
void wl_data_source_add_listener(WlFuncs* api, struct wl_data_source* obj, const struct wl_data_source_listener* listener, void* data) {
  api->proxy_add_listener((struct wl_proxy*)obj, (void(**)(void))listener, data);
}

// wl_data_source - request wrappers.
void wl_data_source_offer(WlFuncs* api, struct wl_data_source* obj, const char* mime_type) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_DATA_SOURCE_OFFER, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, mime_type);
}
void wl_data_source_destroy(WlFuncs* api, struct wl_data_source* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_DATA_SOURCE_DESTROY, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      WL_MARSHAL_FLAG_DESTROY);
}
void wl_data_source_set_actions(WlFuncs* api, struct wl_data_source* obj, u32 dnd_actions) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_DATA_SOURCE_SET_ACTIONS, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, dnd_actions);
}

// wl_data_device - utility wrappers.
u32 wl_data_device_get_version(WlFuncs* api, struct wl_data_device* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}
void wl_data_device_add_listener(WlFuncs* api, struct wl_data_device* obj, const struct wl_data_device_listener* listener, void* data) {
  api->proxy_add_listener((struct wl_proxy*)obj, (void(**)(void))listener, data);
}

// wl_data_device - request wrappers.
void wl_data_device_start_drag(WlFuncs* api, struct wl_data_device* obj, struct wl_data_source* source, struct wl_surface* origin, struct wl_surface* icon, u32 serial) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_DATA_DEVICE_START_DRAG, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, source, origin, icon, serial);
}
void wl_data_device_set_selection(WlFuncs* api, struct wl_data_device* obj, struct wl_data_source* source, u32 serial) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_DATA_DEVICE_SET_SELECTION, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, source, serial);
}
void wl_data_device_release(WlFuncs* api, struct wl_data_device* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_DATA_DEVICE_RELEASE, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      WL_MARSHAL_FLAG_DESTROY);
}

// wl_data_device_manager - utility wrappers.
u32 wl_data_device_manager_get_version(WlFuncs* api, struct wl_data_device_manager* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}
void wl_data_device_manager_destroy(WlFuncs* api, struct wl_data_device_manager* obj) {
  api->proxy_destroy((struct wl_proxy*)obj);
}

// wl_data_device_manager - request wrappers.
struct wl_data_source* wl_data_device_manager_create_data_source(WlFuncs* api, struct wl_data_device_manager* obj) {
  return api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_DATA_DEVICE_MANAGER_CREATE_DATA_SOURCE, &wl_data_source_interface,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, null);
}
struct wl_data_device* wl_data_device_manager_get_data_device(WlFuncs* api, struct wl_data_device_manager* obj, struct wl_seat* seat) {
  return api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_DATA_DEVICE_MANAGER_GET_DATA_DEVICE, &wl_data_device_interface,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, null, seat);
}

// wl_shell - utility wrappers.
u32 wl_shell_get_version(WlFuncs* api, struct wl_shell* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}
void wl_shell_destroy(WlFuncs* api, struct wl_shell* obj) {
  api->proxy_destroy((struct wl_proxy*)obj);
}

// wl_shell - request wrappers.
struct wl_shell_surface* wl_shell_get_shell_surface(WlFuncs* api, struct wl_shell* obj, struct wl_surface* surface) {
  return api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SHELL_GET_SHELL_SURFACE, &wl_shell_surface_interface,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, null, surface);
}

// wl_shell_surface - utility wrappers.
u32 wl_shell_surface_get_version(WlFuncs* api, struct wl_shell_surface* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}
void wl_shell_surface_destroy(WlFuncs* api, struct wl_shell_surface* obj) {
  api->proxy_destroy((struct wl_proxy*)obj);
}
void wl_shell_surface_add_listener(WlFuncs* api, struct wl_shell_surface* obj, const struct wl_shell_surface_listener* listener, void* data) {
  api->proxy_add_listener((struct wl_proxy*)obj, (void(**)(void))listener, data);
}

// wl_shell_surface - request wrappers.
void wl_shell_surface_pong(WlFuncs* api, struct wl_shell_surface* obj, u32 serial) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SHELL_SURFACE_PONG, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, serial);
}
void wl_shell_surface_move(WlFuncs* api, struct wl_shell_surface* obj, struct wl_seat* seat, u32 serial) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SHELL_SURFACE_MOVE, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, seat, serial);
}
void wl_shell_surface_resize(WlFuncs* api, struct wl_shell_surface* obj, struct wl_seat* seat, u32 serial, u32 edges) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SHELL_SURFACE_RESIZE, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, seat, serial, edges);
}
void wl_shell_surface_set_toplevel(WlFuncs* api, struct wl_shell_surface* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SHELL_SURFACE_SET_TOPLEVEL, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0);
}
void wl_shell_surface_set_transient(WlFuncs* api, struct wl_shell_surface* obj, struct wl_surface* parent, i32 x, i32 y, u32 flags) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SHELL_SURFACE_SET_TRANSIENT, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, parent, x, y, flags);
}
void wl_shell_surface_set_fullscreen(WlFuncs* api, struct wl_shell_surface* obj, u32 method, u32 framerate, struct wl_output* output) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SHELL_SURFACE_SET_FULLSCREEN, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, method, framerate, output);
}
void wl_shell_surface_set_popup(WlFuncs* api, struct wl_shell_surface* obj, struct wl_seat* seat, u32 serial, struct wl_surface* parent, i32 x, i32 y, u32 flags) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SHELL_SURFACE_SET_POPUP, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, seat, serial, parent, x, y, flags);
}
void wl_shell_surface_set_maximized(WlFuncs* api, struct wl_shell_surface* obj, struct wl_output* output) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SHELL_SURFACE_SET_MAXIMIZED, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, output);
}
void wl_shell_surface_set_title(WlFuncs* api, struct wl_shell_surface* obj, const char* title) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SHELL_SURFACE_SET_TITLE, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, title);
}
void wl_shell_surface_set_class(WlFuncs* api, struct wl_shell_surface* obj, const char* class_) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SHELL_SURFACE_SET_CLASS, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, class_);
}

// wl_surface - utility wrappers.
u32 wl_surface_get_version(WlFuncs* api, struct wl_surface* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}
void wl_surface_add_listener(WlFuncs* api, struct wl_surface* obj, const struct wl_surface_listener* listener, void* data) {
  api->proxy_add_listener((struct wl_proxy*)obj, (void(**)(void))listener, data);
}

// wl_surface - request wrappers.
void wl_surface_destroy(WlFuncs* api, struct wl_surface* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SURFACE_DESTROY, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      WL_MARSHAL_FLAG_DESTROY);
}
void wl_surface_attach(WlFuncs* api, struct wl_surface* obj, struct wl_buffer* buffer, i32 x, i32 y) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SURFACE_ATTACH, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, buffer, x, y);
}
void wl_surface_damage(WlFuncs* api, struct wl_surface* obj, i32 x, i32 y, i32 width, i32 height) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SURFACE_DAMAGE, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, x, y, width, height);
}
struct wl_callback* wl_surface_frame(WlFuncs* api, struct wl_surface* obj) {
  return api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SURFACE_FRAME, &wl_callback_interface,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, null);
}
void wl_surface_set_opaque_region(WlFuncs* api, struct wl_surface* obj, struct wl_region* region) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SURFACE_SET_OPAQUE_REGION, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, region);
}
void wl_surface_set_input_region(WlFuncs* api, struct wl_surface* obj, struct wl_region* region) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SURFACE_SET_INPUT_REGION, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, region);
}
void wl_surface_commit(WlFuncs* api, struct wl_surface* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SURFACE_COMMIT, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0);
}
void wl_surface_set_buffer_transform(WlFuncs* api, struct wl_surface* obj, i32 transform) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SURFACE_SET_BUFFER_TRANSFORM, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, transform);
}
void wl_surface_set_buffer_scale(WlFuncs* api, struct wl_surface* obj, i32 scale) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SURFACE_SET_BUFFER_SCALE, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, scale);
}
void wl_surface_damage_buffer(WlFuncs* api, struct wl_surface* obj, i32 x, i32 y, i32 width, i32 height) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SURFACE_DAMAGE_BUFFER, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, x, y, width, height);
}
void wl_surface_offset(WlFuncs* api, struct wl_surface* obj, i32 x, i32 y) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SURFACE_OFFSET, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, x, y);
}

// wl_seat - utility wrappers.
u32 wl_seat_get_version(WlFuncs* api, struct wl_seat* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}
void wl_seat_add_listener(WlFuncs* api, struct wl_seat* obj, const struct wl_seat_listener* listener, void* data) {
  api->proxy_add_listener((struct wl_proxy*)obj, (void(**)(void))listener, data);
}

// wl_seat - request wrappers.
struct wl_pointer* wl_seat_get_pointer(WlFuncs* api, struct wl_seat* obj) {
  return api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SEAT_GET_POINTER, &wl_pointer_interface,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, null);
}
struct wl_keyboard* wl_seat_get_keyboard(WlFuncs* api, struct wl_seat* obj) {
  return api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SEAT_GET_KEYBOARD, &wl_keyboard_interface,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, null);
}
struct wl_touch* wl_seat_get_touch(WlFuncs* api, struct wl_seat* obj) {
  return api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SEAT_GET_TOUCH, &wl_touch_interface,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, null);
}
void wl_seat_release(WlFuncs* api, struct wl_seat* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SEAT_RELEASE, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      WL_MARSHAL_FLAG_DESTROY);
}

// wl_pointer - utility wrappers.
u32 wl_pointer_get_version(WlFuncs* api, struct wl_pointer* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}
void wl_pointer_add_listener(WlFuncs* api, struct wl_pointer* obj, const struct wl_pointer_listener* listener, void* data) {
  api->proxy_add_listener((struct wl_proxy*)obj, (void(**)(void))listener, data);
}

// wl_pointer - request wrappers.
void wl_pointer_set_cursor(WlFuncs* api, struct wl_pointer* obj, u32 serial, struct wl_surface* surface, i32 hotspot_x, i32 hotspot_y) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_POINTER_SET_CURSOR, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, serial, surface, hotspot_x, hotspot_y);
}
void wl_pointer_release(WlFuncs* api, struct wl_pointer* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_POINTER_RELEASE, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      WL_MARSHAL_FLAG_DESTROY);
}

// wl_keyboard - utility wrappers.
u32 wl_keyboard_get_version(WlFuncs* api, struct wl_keyboard* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}
void wl_keyboard_add_listener(WlFuncs* api, struct wl_keyboard* obj, const struct wl_keyboard_listener* listener, void* data) {
  api->proxy_add_listener((struct wl_proxy*)obj, (void(**)(void))listener, data);
}

// wl_keyboard - request wrappers.
void wl_keyboard_release(WlFuncs* api, struct wl_keyboard* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_KEYBOARD_RELEASE, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      WL_MARSHAL_FLAG_DESTROY);
}

// wl_touch - utility wrappers.
u32 wl_touch_get_version(WlFuncs* api, struct wl_touch* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}
void wl_touch_add_listener(WlFuncs* api, struct wl_touch* obj, const struct wl_touch_listener* listener, void* data) {
  api->proxy_add_listener((struct wl_proxy*)obj, (void(**)(void))listener, data);
}

// wl_touch - request wrappers.
void wl_touch_release(WlFuncs* api, struct wl_touch* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_TOUCH_RELEASE, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      WL_MARSHAL_FLAG_DESTROY);
}

// wl_output - utility wrappers.
u32 wl_output_get_version(WlFuncs* api, struct wl_output* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}
void wl_output_add_listener(WlFuncs* api, struct wl_output* obj, const struct wl_output_listener* listener, void* data) {
  api->proxy_add_listener((struct wl_proxy*)obj, (void(**)(void))listener, data);
}

// wl_output - request wrappers.
void wl_output_release(WlFuncs* api, struct wl_output* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_OUTPUT_RELEASE, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      WL_MARSHAL_FLAG_DESTROY);
}

// wl_region - utility wrappers.
u32 wl_region_get_version(WlFuncs* api, struct wl_region* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}

// wl_region - request wrappers.
void wl_region_destroy(WlFuncs* api, struct wl_region* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_REGION_DESTROY, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      WL_MARSHAL_FLAG_DESTROY);
}
void wl_region_add(WlFuncs* api, struct wl_region* obj, i32 x, i32 y, i32 width, i32 height) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_REGION_ADD, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, x, y, width, height);
}
void wl_region_subtract(WlFuncs* api, struct wl_region* obj, i32 x, i32 y, i32 width, i32 height) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_REGION_SUBTRACT, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, x, y, width, height);
}

// wl_subcompositor - utility wrappers.
u32 wl_subcompositor_get_version(WlFuncs* api, struct wl_subcompositor* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}

// wl_subcompositor - request wrappers.
void wl_subcompositor_destroy(WlFuncs* api, struct wl_subcompositor* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SUBCOMPOSITOR_DESTROY, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      WL_MARSHAL_FLAG_DESTROY);
}
struct wl_subsurface* wl_subcompositor_get_subsurface(WlFuncs* api, struct wl_subcompositor* obj, struct wl_surface* surface, struct wl_surface* parent) {
  return api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SUBCOMPOSITOR_GET_SUBSURFACE, &wl_subsurface_interface,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, null, surface, parent);
}

// wl_subsurface - utility wrappers.
u32 wl_subsurface_get_version(WlFuncs* api, struct wl_subsurface* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}

// wl_subsurface - request wrappers.
void wl_subsurface_destroy(WlFuncs* api, struct wl_subsurface* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SUBSURFACE_DESTROY, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      WL_MARSHAL_FLAG_DESTROY);
}
void wl_subsurface_set_position(WlFuncs* api, struct wl_subsurface* obj, i32 x, i32 y) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SUBSURFACE_SET_POSITION, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, x, y);
}
void wl_subsurface_place_above(WlFuncs* api, struct wl_subsurface* obj, struct wl_surface* sibling) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SUBSURFACE_PLACE_ABOVE, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, sibling);
}
void wl_subsurface_place_below(WlFuncs* api, struct wl_subsurface* obj, struct wl_surface* sibling) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SUBSURFACE_PLACE_BELOW, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, sibling);
}
void wl_subsurface_set_sync(WlFuncs* api, struct wl_subsurface* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SUBSURFACE_SET_SYNC, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0);
}
void wl_subsurface_set_desync(WlFuncs* api, struct wl_subsurface* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_SUBSURFACE_SET_DESYNC, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0);
}

// wl_fixes - utility wrappers.
u32 wl_fixes_get_version(WlFuncs* api, struct wl_fixes* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}

// wl_fixes - request wrappers.
void wl_fixes_destroy(WlFuncs* api, struct wl_fixes* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_FIXES_DESTROY, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      WL_MARSHAL_FLAG_DESTROY);
}
void wl_fixes_destroy_registry(WlFuncs* api, struct wl_fixes* obj, struct wl_registry* registry) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, WL_FIXES_DESTROY_REGISTRY, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, registry);
}

// xdg_wm_base - utility wrappers.
u32 xdg_wm_base_get_version(WlFuncs* api, struct xdg_wm_base* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}
void xdg_wm_base_add_listener(WlFuncs* api, struct xdg_wm_base* obj, const struct xdg_wm_base_listener* listener, void* data) {
  api->proxy_add_listener((struct wl_proxy*)obj, (void(**)(void))listener, data);
}

// xdg_wm_base - request wrappers.
void xdg_wm_base_destroy(WlFuncs* api, struct xdg_wm_base* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_WM_BASE_DESTROY, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      WL_MARSHAL_FLAG_DESTROY);
}
struct xdg_positioner* xdg_wm_base_create_positioner(WlFuncs* api, struct xdg_wm_base* obj) {
  return api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_WM_BASE_CREATE_POSITIONER, &xdg_positioner_interface,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, null);
}
struct xdg_surface* xdg_wm_base_get_xdg_surface(WlFuncs* api, struct xdg_wm_base* obj, struct wl_surface* surface) {
  return api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_WM_BASE_GET_XDG_SURFACE, &xdg_surface_interface,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, null, surface);
}
void xdg_wm_base_pong(WlFuncs* api, struct xdg_wm_base* obj, u32 serial) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_WM_BASE_PONG, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, serial);
}

// xdg_positioner - utility wrappers.
u32 xdg_positioner_get_version(WlFuncs* api, struct xdg_positioner* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}

// xdg_positioner - request wrappers.
void xdg_positioner_destroy(WlFuncs* api, struct xdg_positioner* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_POSITIONER_DESTROY, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      WL_MARSHAL_FLAG_DESTROY);
}
void xdg_positioner_set_size(WlFuncs* api, struct xdg_positioner* obj, i32 width, i32 height) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_POSITIONER_SET_SIZE, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, width, height);
}
void xdg_positioner_set_anchor_rect(WlFuncs* api, struct xdg_positioner* obj, i32 x, i32 y, i32 width, i32 height) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_POSITIONER_SET_ANCHOR_RECT, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, x, y, width, height);
}
void xdg_positioner_set_anchor(WlFuncs* api, struct xdg_positioner* obj, u32 anchor) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_POSITIONER_SET_ANCHOR, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, anchor);
}
void xdg_positioner_set_gravity(WlFuncs* api, struct xdg_positioner* obj, u32 gravity) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_POSITIONER_SET_GRAVITY, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, gravity);
}
void xdg_positioner_set_constraint_adjustment(WlFuncs* api, struct xdg_positioner* obj, u32 constraint_adjustment) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_POSITIONER_SET_CONSTRAINT_ADJUSTMENT, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, constraint_adjustment);
}
void xdg_positioner_set_offset(WlFuncs* api, struct xdg_positioner* obj, i32 x, i32 y) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_POSITIONER_SET_OFFSET, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, x, y);
}
void xdg_positioner_set_reactive(WlFuncs* api, struct xdg_positioner* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_POSITIONER_SET_REACTIVE, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0);
}
void xdg_positioner_set_parent_size(WlFuncs* api, struct xdg_positioner* obj, i32 parent_width, i32 parent_height) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_POSITIONER_SET_PARENT_SIZE, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, parent_width, parent_height);
}
void xdg_positioner_set_parent_configure(WlFuncs* api, struct xdg_positioner* obj, u32 serial) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_POSITIONER_SET_PARENT_CONFIGURE, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, serial);
}

// xdg_surface - utility wrappers.
u32 xdg_surface_get_version(WlFuncs* api, struct xdg_surface* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}
void xdg_surface_add_listener(WlFuncs* api, struct xdg_surface* obj, const struct xdg_surface_listener* listener, void* data) {
  api->proxy_add_listener((struct wl_proxy*)obj, (void(**)(void))listener, data);
}

// xdg_surface - request wrappers.
void xdg_surface_destroy(WlFuncs* api, struct xdg_surface* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_SURFACE_DESTROY, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      WL_MARSHAL_FLAG_DESTROY);
}
struct xdg_toplevel* xdg_surface_get_toplevel(WlFuncs* api, struct xdg_surface* obj) {
  return api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_SURFACE_GET_TOPLEVEL, &xdg_toplevel_interface,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, null);
}
struct xdg_popup* xdg_surface_get_popup(WlFuncs* api, struct xdg_surface* obj, struct xdg_surface* parent, struct xdg_positioner* positioner) {
  return api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_SURFACE_GET_POPUP, &xdg_popup_interface,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, null, parent, positioner);
}
void xdg_surface_set_window_geometry(WlFuncs* api, struct xdg_surface* obj, i32 x, i32 y, i32 width, i32 height) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_SURFACE_SET_WINDOW_GEOMETRY, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, x, y, width, height);
}
void xdg_surface_ack_configure(WlFuncs* api, struct xdg_surface* obj, u32 serial) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_SURFACE_ACK_CONFIGURE, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, serial);
}

// xdg_toplevel - utility wrappers.
u32 xdg_toplevel_get_version(WlFuncs* api, struct xdg_toplevel* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}
void xdg_toplevel_add_listener(WlFuncs* api, struct xdg_toplevel* obj, const struct xdg_toplevel_listener* listener, void* data) {
  api->proxy_add_listener((struct wl_proxy*)obj, (void(**)(void))listener, data);
}

// xdg_toplevel - request wrappers.
void xdg_toplevel_destroy(WlFuncs* api, struct xdg_toplevel* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_TOPLEVEL_DESTROY, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      WL_MARSHAL_FLAG_DESTROY);
}
void xdg_toplevel_set_parent(WlFuncs* api, struct xdg_toplevel* obj, struct xdg_toplevel* parent) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_TOPLEVEL_SET_PARENT, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, parent);
}
void xdg_toplevel_set_title(WlFuncs* api, struct xdg_toplevel* obj, const char* title) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_TOPLEVEL_SET_TITLE, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, title);
}
void xdg_toplevel_set_app_id(WlFuncs* api, struct xdg_toplevel* obj, const char* app_id) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_TOPLEVEL_SET_APP_ID, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, app_id);
}
void xdg_toplevel_show_window_menu(WlFuncs* api, struct xdg_toplevel* obj, struct wl_seat* seat, u32 serial, i32 x, i32 y) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_TOPLEVEL_SHOW_WINDOW_MENU, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, seat, serial, x, y);
}
void xdg_toplevel_move(WlFuncs* api, struct xdg_toplevel* obj, struct wl_seat* seat, u32 serial) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_TOPLEVEL_MOVE, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, seat, serial);
}
void xdg_toplevel_resize(WlFuncs* api, struct xdg_toplevel* obj, struct wl_seat* seat, u32 serial, u32 edges) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_TOPLEVEL_RESIZE, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, seat, serial, edges);
}
void xdg_toplevel_set_max_size(WlFuncs* api, struct xdg_toplevel* obj, i32 width, i32 height) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_TOPLEVEL_SET_MAX_SIZE, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, width, height);
}
void xdg_toplevel_set_min_size(WlFuncs* api, struct xdg_toplevel* obj, i32 width, i32 height) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_TOPLEVEL_SET_MIN_SIZE, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, width, height);
}
void xdg_toplevel_set_maximized(WlFuncs* api, struct xdg_toplevel* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_TOPLEVEL_SET_MAXIMIZED, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0);
}
void xdg_toplevel_unset_maximized(WlFuncs* api, struct xdg_toplevel* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_TOPLEVEL_UNSET_MAXIMIZED, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0);
}
void xdg_toplevel_set_fullscreen(WlFuncs* api, struct xdg_toplevel* obj, struct wl_output* output) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_TOPLEVEL_SET_FULLSCREEN, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, output);
}
void xdg_toplevel_unset_fullscreen(WlFuncs* api, struct xdg_toplevel* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_TOPLEVEL_UNSET_FULLSCREEN, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0);
}
void xdg_toplevel_set_minimized(WlFuncs* api, struct xdg_toplevel* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_TOPLEVEL_SET_MINIMIZED, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0);
}

// xdg_popup - utility wrappers.
u32 xdg_popup_get_version(WlFuncs* api, struct xdg_popup* obj) {
  return api->proxy_get_version((struct wl_proxy*)obj);
}
void xdg_popup_add_listener(WlFuncs* api, struct xdg_popup* obj, const struct xdg_popup_listener* listener, void* data) {
  api->proxy_add_listener((struct wl_proxy*)obj, (void(**)(void))listener, data);
}

// xdg_popup - request wrappers.
void xdg_popup_destroy(WlFuncs* api, struct xdg_popup* obj) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_POPUP_DESTROY, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      WL_MARSHAL_FLAG_DESTROY);
}
void xdg_popup_grab(WlFuncs* api, struct xdg_popup* obj, struct wl_seat* seat, u32 serial) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_POPUP_GRAB, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, seat, serial);
}
void xdg_popup_reposition(WlFuncs* api, struct xdg_popup* obj, struct xdg_positioner* positioner, u32 token) {
  api->proxy_marshal_flags(
      (struct wl_proxy*)obj, XDG_POPUP_REPOSITION, null,
      api->proxy_get_version((struct wl_proxy*)obj),
      0, positioner, token);
}

// clang-format on
