#pragma once
// Generated by 'idgen'.

// clang-format off
enum {
  ScriptId_any = 119688326, // any
  ScriptId_if = 3180054279, // if
  ScriptId_else = 1760833515, // else
  ScriptId_var = 172593793, // var
  ScriptId_while = 1492262353, // while
  ScriptId_continue = 1788505286, // continue
  ScriptId_break = 1725904472, // break
  ScriptId_for = 327857603, // for
  ScriptId_return = 3227182607, // return
};
// clang-format on
