#pragma once
// Generated by 'idgen'.

// clang-format off
enum {
  GameId_Game = 2551442255, // Game
  GameId_Edit = 2684623067, // Edit
  GameId_Dev = 2547616407, // Dev
  GameId_minimap = 3582479288, // minimap
  GameId_Pause = 152424741, // Pause
  GameId_CameraReset = 476230800, // CameraReset
  GameId_OrderStop = 3674266003, // OrderStop
  GameId_EffectIndicatorMove = 1884579441, // EffectIndicatorMove
  GameId_EffectIndicatorAttack = 3489365775, // EffectIndicatorAttack
  GameId_HUD_FACTION_PLAYER = 1256886660, // HUD_FACTION_PLAYER
  GameId_HUD_FACTION_ENEMY = 2203697841, // HUD_FACTION_ENEMY
  GameId_HUD_PAUSE_TOOLTIP = 3446584280, // HUD_PAUSE_TOOLTIP
  GameId_HUD_CAMERA_RESET_TOOLTIP = 1607900573, // HUD_CAMERA_RESET_TOOLTIP
  GameId_HUD_ORDER_STOP_TOOLTIP = 446685756, // HUD_ORDER_STOP_TOOLTIP
};
// clang-format on
