
var fixture         = self()
var fixtureEmissive = 0.25
var lightRadius     = 5
var lightIntensity  = 3.5
var lightOffset     = vec3(0.25, 0.5, 0)

rend_param(fixture, "Emissive", $color ? fixtureEmissive : 0.0)
rend_param(fixture, "Color", $color ?? white)

if ($light) {
  light_param($light, "Radiance", ($color ?? black) * lightIntensity)
} else {
  var e = light_point_spawn(vec3(0, 0, 0), black, lightRadius)
  attach(e, fixture, null, lightOffset)
  destroy_after(e, fixture)
  $light = e
}
