
var me = self()

if (active(me, "Dead")) {
  return
}

if (!exists($cmdAttackTarget)) {
  $cmdAttackTarget = null
}

if ($cmdAttackTarget && {
    var dist = distance(position($cmdAttackTarget), position(me))
    dist < target_range_min(me) || dist > target_range_max(me)
  }) {
  $cmdAttackTarget = null
}

var target = $cmdAttackTarget ?? target_primary(me)
if (target && health(target) > 0) {
  attack(me, target)
}
