
var me = self()

if (active(me, "Dead")) {
  return
}

if (!exists($user_attack_target)) {
  $user_attack_target = null
}

var target = $user_attack_target ?? target_primary(me)
if (target && health(target) > 0) {
  var losRadius = 0.5
  var los       = line_of_sight(me, target, losRadius)
  if (los != null && los <= target_range_max(me)) {
    attack(me, target)
  } else {
    attack(me, null)
  }
}
