#include "vulkan_api.h"
// Generated by 'app_vkgen' from 'raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/refs/tags/v1.4.308/xml/vk.xml'.
// Copyright 2015-2025 The Khronos Group Inc. SPDX-License-Identifier: Apache-2.0 OR MIT .
// clang-format off

// clang-format on
