
/**
 * Ambiance effects.
 *
 * Supports the following input knowledge:
 * - "assetSndAmbiance": Looping ambiance sound effect.
 */

if ($assetSndAmbiance && !$sndAmbiance) {
  var soundPos     = null // 2d sound.
  var soundGain    = 0.4
  var soundPitch   = 1.0
  var soundLooping = true
  $sndAmbiance     = sound_spawn($assetSndAmbiance, soundPos, soundGain, soundPitch, soundLooping)
  destroy_after($sndAmbiance, self())
}
