
/**
 * Script for testing trail decals, uses the input position as the trail head.
 *
 * Supports the following input knowledge:
 * - "assetDecalTrail": Trail decal asset.
 */

var inputPos = debug_input_position("Environment", "Structure") ?? vec3(0, 0, 0)
var inputRot = debug_input_rotation("Environment", "Structure") ?? quat_ident

if (!$decalTrail && $assetDecalTrail) {
  var alpha   = 1.0
  $decalTrail = vfx_decal_spawn($assetDecalTrail, inputPos, inputRot, alpha)
}

if ($decalTrail) {
  teleport($decalTrail, inputPos, inputRot)
}
