#pragma once
#include "core/string.h"

// Template for the 'version_internal.h' header, will be generated by cmake.

// clang-format off
#define VOLO_VER_MAJOR 0
#define VOLO_VER_MINOR 1
#define VOLO_VER_PATCH 0
#define VOLO_VER_LABEL string_lit("")
// clang-format on
