#pragma once
// Generated by 'idgen'.

// clang-format off
enum {
  DevId_Dev = 2547616407, // Dev
  DevId_Debug = 1184290027, // Debug
  DevId_DevGridScaleDown = 2962200988, // DevGridScaleDown
  DevId_DevGridScaleUp = 3882419195, // DevGridScaleUp
  DevId_DevGridShow = 72213415, // DevGridShow
  DevId_DevInspectorDestroy = 855114851, // DevInspectorDestroy
  DevId_DevInspectorDrop = 1409428543, // DevInspectorDrop
  DevId_DevInspectorDuplicate = 768886120, // DevInspectorDuplicate
  DevId_DevInspectorPickerClose = 600620721, // DevInspectorPickerClose
  DevId_DevInspectorSelectAll = 1629829770, // DevInspectorSelectAll
  DevId_DevInspectorToggleNavLayer = 1634233509, // DevInspectorToggleNavLayer
  DevId_DevInspectorToggleSpace = 2338274085, // DevInspectorToggleSpace
  DevId_DevInspectorToolRotation = 767109130, // DevInspectorToolRotation
  DevId_DevInspectorToolScale = 772314741, // DevInspectorToolScale
  DevId_DevInspectorToolTranslation = 3925386453, // DevInspectorToolTranslation
  DevId_DevInspectorVisAttack = 1069027844, // DevInspectorVisAttack
  DevId_DevInspectorVisCollision = 1793676054, // DevInspectorVisCollision
  DevId_DevInspectorVisHealth = 3895311548, // DevInspectorVisHealth
  DevId_DevInspectorVisIcon = 1634548357, // DevInspectorVisIcon
  DevId_DevInspectorVisLight = 3803428553, // DevInspectorVisLight
  DevId_DevInspectorVisLocomotion = 2458237107, // DevInspectorVisLocomotion
  DevId_DevInspectorVisMode = 3917645724, // DevInspectorVisMode
  DevId_DevInspectorVisName = 685338671, // DevInspectorVisName
  DevId_DevInspectorVisNavigationGrid = 1035447104, // DevInspectorVisNavigationGrid
  DevId_DevInspectorVisNavigationPath = 698286930, // DevInspectorVisNavigationPath
  DevId_DevInspectorVisTarget = 3170194590, // DevInspectorVisTarget
  DevId_DevInspectorVisVision = 1006273319, // DevInspectorVisVision
  DevId_DevPanelClose = 3611106621, // DevPanelClose
  DevId_DevPanelEcs = 2791786667, // DevPanelEcs
  DevId_DevPanelHierarchy = 345095034, // DevPanelHierarchy
  DevId_DevPanelInspector = 3688163297, // DevPanelInspector
  DevId_DevPanelLevel = 1279901324, // DevPanelLevel
  DevId_DevPanelPrefab = 205469752, // DevPanelPrefab
  DevId_DevPanelRenderer = 2341646233, // DevPanelRenderer
  DevId_DevPanelScript = 3118876660, // DevPanelScript
  DevId_DevPanelSkeleton = 3621104430, // DevPanelSkeleton
  DevId_DevPanelSound = 4051400737, // DevPanelSound
  DevId_DevPanelTime = 1086967750, // DevPanelTime
  DevId_DevPanelTrace = 1438144397, // DevPanelTrace
  DevId_DevTimePauseToggle = 2088614054, // DevTimePauseToggle
  DevId_DevTimeScaleDown = 4137843889, // DevTimeScaleDown
  DevId_DevTimeScaleUp = 3973438992, // DevTimeScaleUp
  DevId_DevTimeStep = 3334101101, // DevTimeStep
  DevId_DevPrefabCreate = 4132903015, // DevPrefabCreate
  DevId_DevPrefabCreateCancel = 3047481622, // DevPrefabCreateCancel
};
// clang-format on
