/**
 * Spawn a unit that attacks an endlessly respawning explosive barrel.
 */

var origin = position(self())

$unit ??= {
  var pos   = nav_find(origin, "Normal", "UnblockedCell")
  var rot   = quat_ident
  var scale = 1.0
  prefab_spawn("InfantryRifle", pos, rot, scale, "FactionA")
}

if (exists($target)) {
  attack($unit, $target)
} else {
  var radius = 20
  var pos    = nav_find(origin + random_circle_xz() * radius)
  var rot    = quat_ident
  var scale  = 1.0
  $target    = prefab_spawn("PropBarrelExplosive", pos, rot, scale, "FactionNone")
}
