
var origin = position(self()) + vec3(0, 2.5, 0)

if ($init) {
  var speed     = 3.0
  var noiseFreq = 0.5
  for (var lights = query_set("myLights"); var light = query_pop(lights);) {
    var pos = position(light)
    var dir = angle_axis(perlin3(pos * noiseFreq) * pi * 2, up) * forward

    teleport(light, pos + dir * speed * time("Delta"))
  }
} else {
  var intensity   = 3.0
  var lightRadius = 12.5
  var spawnCount  = 250
  var spawnRadius = 50
  for (var i = 0; i != spawnCount; i += 1) {
    var pos      = origin + random_circle_xz() * spawnRadius
    var radiance = color_hsv(random(), 1, 1, 1) * intensity
    var light    = light_point(pos, radiance, lightRadius)
    set(light, "myLights", true)
  }
  $init = true
}
