
/**
 * Script for testing trail decals, uses the input position as the trail head.
 *
 * Supports the following input properties:
 * - "assetDecalTrail": Trail decal asset.
 */

var inputPos = debug_input_position(null, "Environment", "Structure") ?? vec3(0, 0, 0)

if (!$decalTrail && $assetDecalTrail) {
  var alpha   = 1.0
  $decalTrail = vfx_decal_spawn($assetDecalTrail, inputPos, quat_ident, alpha)
}

if ($decalTrail) {
  teleport($decalTrail, inputPos, quat_ident)
}
