/**
 * Generic texture import rules applicable to all textures.
 */

if (asset_id_match("*_normal*") || asset_id_match("*_nrm*")) {
  fail_if(texture_channels() < 3, "Normal maps require 3 channels")
  texture_flag("NormalMap", true)
}
if (asset_id_match("*_lossless*")) {
  texture_flag("Lossless", true)
}
if (asset_id_match("*_linear*")) {
  texture_flag("Linear", true)
}

var warnSize = 2048
if (texture_width() > warnSize || texture_height() > warnSize) {
  warn("Unusually large texture")
}
