name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.image}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: linux,
            image: ubuntu-24.04,
            os: linux,
            toolchain: unix,
            cc: clang-18,
            shaderc: libshaderc_shared.so.1
          }
        - {
            name: windows,
            image: windows-2025,
            os: windows,
            toolchain: msvc,
            cc: clang,
            shaderc: shaderc_shared.dll
          }
    env:
      CC: ${{matrix.config.cc}}
      CMAKE_OPTS: >-
        -DFAST=On
        -DSIMD=On
        -DLTO=On
        -DTRACE=Off
        -DSANITIZE=Off
      SHADERC: ${{matrix.config.shaderc}}
      SHADERC_URL: https://bastian.tech/redist/${{matrix.config.os}}-x64/${{matrix.config.shaderc}}
      LD_LIBRARY_PATH: ${{github.workspace}}/deps
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: deps-cache
      uses: actions/cache@v4
      with:
        key: deps-${{matrix.config.image}}-001
        path: deps

    - name: deps-fetch
      if: ${{steps.deps-cache.outputs.cache-hit != 'true'}}
      shell: bash
      run: |
        mkdir "$GITHUB_WORKSPACE/deps"
        curl -o "$GITHUB_WORKSPACE/deps/$SHADERC" $SHADERC_URL

    - name: deps-prepare
      shell: bash
      run: echo "$GITHUB_WORKSPACE/deps" >> "$GITHUB_PATH"

    - name: assets-cache
      uses: actions/cache@v4
      with:
        key: assets-${{github.sha}}
        restore-keys: assets-
        enableCrossOsArchive: true
        path: |
          assets/.cache
          assets/external

    - name: build-unix
      if: matrix.config.toolchain == 'unix'
      shell: bash
      run: |
        cmake -B build $CMAKE_OPTS &&
        make -s -C build app_game run.fetch run.pack

    - name: build-msvc
      if: matrix.config.toolchain == 'msvc'
      shell: pwsh
      run: |
        ./ci/env-win32.ps1                                                &&
        cmake -B build -G 'NMake Makefiles' $($env:CMAKE_OPTS -split ' ') &&
        cd build                                                          &&
        nmake /C app_game run.fetch run.pack
