name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-code:
    name: build-${{matrix.config.name}}
    runs-on: ${{matrix.config.image}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: linux-dev-gcc-x64,
            image: ubuntu-24.04,
            os: linux,
            toolchain: unix,
            cc: gcc-14,
            fast: Off,
            simd: On,
            trace: On,
            lto: Off,
            sanitize: On,
          }
        - {
            name: linux-dev-gcc-no-simd-x64,
            image: ubuntu-24.04,
            os: linux,
            toolchain: unix,
            cc: gcc-14,
            fast: Off,
            simd: Off,
            trace: On,
            lto: Off,
            sanitize: On,
          }
        - {
            name: linux-dev-clang-x64,
            image: ubuntu-24.04,
            os: linux,
            toolchain: unix,
            cc: clang-18,
            fast: Off,
            simd: On,
            trace: On,
            lto: Off,
            sanitize: On,
          }
        - {
            name: windows-dev-msvc-x64,
            image: windows-2025,
            os: windows,
            toolchain: msvc,
            cc: cl,
            fast: Off,
            simd: On,
            trace: On,
            lto: Off,
            sanitize: On,
          }
        - {
            name: windows-dev-clang-x64,
            image: windows-2025,
            os: windows,
            toolchain: msvc,
            cc: clang,
            fast: Off,
            simd: On,
            trace: On,
            lto: Off,
            sanitize: On,
          }
        - {
            name: windows-dev-mingw-x64,
            image: windows-2025,
            os: windows,
            toolchain: mingw,
            cc: gcc,
            fast: Off,
            simd: On,
            trace: On,
            lto: Off,
            sanitize: On,
          }
        - {
            name: linux-rel-x64,
            image: ubuntu-24.04,
            os: linux,
            toolchain: unix,
            cc: clang-18,
            fast: On,
            simd: On,
            trace: Off,
            lto: On,
            sanitize: Off,
          }
        - {
            name: windows-rel-x64,
            image: windows-2025,
            os: windows,
            toolchain: msvc,
            cc: clang,
            fast: On,
            simd: On,
            trace: Off,
            lto: On,
            sanitize: Off,
          }
    env:
      CC: ${{matrix.config.cc}}
      CMAKE_OPTS: >-
        -DLABEL=${{github.sha}}
        -DFAST=${{matrix.config.fast}}
        -DSIMD=${{matrix.config.simd}}
        -DLTO=${{matrix.config.lto}}
        -DTRACE=${{matrix.config.trace}}
        -DSANITIZE=${{matrix.config.sanitize}}
    steps:
    - name: checkout
      uses: actions/checkout@v5
      with:
        sparse-checkout: |
          ci
          cmake
          volo
          libs
          utilities

    - name: build-unix
      if: matrix.config.toolchain == 'unix'
      shell: bash
      run: |
        cmake -B build $CMAKE_OPTS
        make -sk -C build all test install

    - name: build-msvc
      if: matrix.config.toolchain == 'msvc'
      shell: pwsh
      run: |
        ./ci/env-win32.ps1
        cmake -B build -G 'NMake Makefiles' $($env:CMAKE_OPTS -split ' ')
        Push-Location build; nmake /C /K all test install; Pop-Location

    - name: build-mingw
      if: matrix.config.toolchain == 'mingw'
      shell: pwsh
      run: |
        cmake -B build -G 'MinGW Makefiles' $($env:CMAKE_OPTS -split ' ')
        mingw32-make -sk -C build all test install

    - name: build-symbols
      if: matrix.config.toolchain != 'mingw'
      shell: bash
      run: ./bin/volo --debug-symbols > ./bin/volo.syms

    - name: strip-unix
      if: matrix.config.toolchain == 'unix'
      shell: bash
      run: |
        for file in $(find bin -type f ! -name "*.*"); do
            objcopy --only-keep-debug "$file" "$file.dbg"
            strip --strip-all "$file"
            objcopy --add-gnu-debuglink="$file.dbg" "$file"
        done

    - name: archive
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: code-${{matrix.config.name}}
        path: |
          bin/
          build/**/logs/*

    - name: report
      uses: dorny/test-reporter@v2
      if: ${{ !cancelled() }}
      with:
        name: report-${{matrix.config.name}}
        fail-on-error: false
        path: build/**/logs/*.mocha
        reporter: mocha-json
        only-summary: 'true'

  build-assets:
    needs: build-code
    runs-on: ubuntu-24.04
    env:
      REDIST_URL: https://bastian.tech/redist/linux-x64
      LD_LIBRARY_PATH: ${{github.workspace}}/deps
    steps:
    - name: checkout
      uses: actions/checkout@v5
      with:
        sparse-checkout: assets

    - name: code-init
      uses: actions/download-artifact@v4
      with:
        name: code-linux-rel-x64

    - name: deps-cache
      id: deps-cache
      uses: actions/cache@v4
      with:
        key: deps-linux-001
        path: deps

    - name: deps-init
      if: ${{steps.deps-cache.outputs.cache-hit != 'true'}}
      shell: bash
      run: |
        mkdir "$GITHUB_WORKSPACE/deps"
        curl -o "$GITHUB_WORKSPACE/deps/libshaderc_shared.so.1" $REDIST_URL/libshaderc_shared.so.1

    - name: assets-cache
      id: assets-cache
      uses: actions/cache@v4
      with:
        key: assets-${{github.sha}}
        restore-keys: assets-
        enableCrossOsArchive: true
        path: |
          assets/.cache
          assets/external

    - name: pack
      shell: bash
      run: |
        chmod +x bin/*
        ./bin/fetch assets/fetch.json
        ./bin/pack assets/pack.json --output assets.blob

    - name: archive
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: assets
        path: |
          assets.blob
          bin/**/logs/*
