name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    name: test-${{matrix.config.image}}-${{matrix.config.cc}}
    runs-on: ${{matrix.config.image}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            image: ubuntu-20.04,
            cc: gcc-9,
          }
        - {
            image: ubuntu-20.04,
            cc: gcc-10,
          }
        - {
            image: ubuntu-20.04,
            cc: clang-10,
          }
        - {
            image: ubuntu-20.04,
            cc: clang-12,
          }
    env:
      CC: ${{matrix.config.cc}}
    steps:
    - name: setup-unix
      if: matrix.config.os != 'windows'
      run: |
        echo "Installing ninja..."; sudo apt install ninja-build; ninja --version

    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: configure
      run: cmake -B build -G Ninja

    - name: build
      run: ninja -C build

    - name: test
      run: ninja -C build test
