name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    name: test-${{matrix.config.os}}-${{matrix.config.cc-name}}
    runs-on: ${{matrix.config.image}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            image: ubuntu-20.04,
            os: linux,
            cc-name: gcc,
            cc: gcc-9,
          }
        - {
            image: ubuntu-20.04,
            os: linux,
            cc-name: clang,
            cc: clang-10,
          }
    env:
      CC: ${{matrix.config.cc}}
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: test-linux
      if: matrix.config.os == 'linux'
      run: |
        cmake -B build && make -C build --keep-going --no-print-directory test
