name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    name: test-${{matrix.config.os}}-${{matrix.config.cc}}
    runs-on: ${{matrix.config.image}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            image: ubuntu-20.04,
            os: linux,
            cc: gcc-9,
          }
        - {
            image: ubuntu-20.04,
            os: linux,
            cc: clang-10,
          }
        - {
            image: windows-2019,
            os: windows,
            cc: cl,
          }
    env:
      CC: ${{matrix.config.cc}}
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: test-linux
      if: matrix.config.os == 'linux'
      run: |
        cmake -B build  &&
        cd build        &&
        make -k test

    - name: test-windows-cl
      if: matrix.config.os == 'windows' && matrix.config.cc == 'cl'
      run: |
        ./scripts/msvc-env.ps1              &&
        cmake -B build -G 'NMake Makefiles' &&
        cd build                            &&
        nmake /C /K test
